### PR TITLE
Last Updated Timestamp for visbuilder savedobject is getting Generated

### LINKED ISSUE #2463: [BUG][VisBuilder] Last updated timestamp missing in visualization list
**Describe the bug**

Last updated timestamp missing in visualization list

image

**To Reproduce**
1. Create a VisBuilder visualization
2. Go to Visualize
3. Search for the new visualization
4. See the missing timestamp

**Expected behavior**
Timestamp should be present

**OpenSearch Version**
2.3

**Dashboards Version**
2.3

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

### PR DESCRIPTION
**Pull request by AbhishekReddy1127**
Signed-off-by: AbhishekReddy1127 <nallamsa@amazon.com>

### Description
The Savedobjects for the VisBuilder are generating the last updated timestamp
**ScreenShot**:
Screen Shot 2022-10-19 at 2 42 09 PM

 
### Issues Resolved
#2463 
 
### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

File: src/plugins/vis_builder/public/plugin.ts [hunk 1]
```diff
@@ -120,7 +120,7 @@ export class WizardPlugin
       appExtensions: {
         visualizations: {
           docTypes: [PLUGIN_ID],
-          toListItem: ({ id, attributes }) => ({
+          toListItem: ({ id, attributes, updated_at }) => ({
```
Comment (ashwin-pc) [inline src/plugins/vis_builder/public/plugin.ts:123]: This is a known lint error. Since we cant do much to change the `updated_at` naming convention, alias this as `updated_at: updatedAt` here and reassign it on line 133 as `updated_at: updatedAt`. This should get around the lint error

**Review by ashwin-pc — APPROVED** [review]

**Review by ananzh — APPROVED** [review]
LGTM

**Comment by ananzh** [comment]
@AbhishekReddy1127 This is great and such a cool bean. Currently PR is outdated and you could rebase it. I could approve again after you rebase and solve the conflict.s

**Comment by kavilla** [comment]
@AbhishekReddy1127 would you be able to rebase this PR? Let us know if you need some assistance with that! Thanks!

**Review by ashwin-pc — APPROVED** [review]

**Review by abbyhu2000 — APPROVED** [review]
