### PR TITLE
[MD] Wrap datasource errors for route handlers to understand

### LINKED ISSUE #2210: [BUG] OSD returns HTTP 500 internal server error messages when the wrapping key is changed
OSD returns HTTP 500 internal server error messages when the wrapping key is changed and the service is unable to decrypt the credentials. When the user does not update the credentials and attempts to create a new index pattern, the calls to the target endpoint fails and return HTTP 500 errors. A generic error message is returned in response. 

The recommendation will be to return an error message or at least a suggestion to the user asking to verify if the credentials have been updated post changes to the wrapping key.

### PR DESCRIPTION
**Pull request by zhongnansu**
Signed-off-by: Su <szhongna@amazon.com>

### Description
- remove useless and redundant try catch
- create `DataSourceConfigError`, which cast all 4xx to 400 and all 5xx to 400, and assign a 400 for non savedObjectClient error
- Refactor `router.ts` to conditionally deal with 400 DataSourceClientError
- TODO： 
  - [ ] UI side pop-ups, alarm messages.

image
image
image

 
### Issues Resolved
#2210 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
    - [ ] `yarn test:jest`
    - [ ] `yarn test:jest_integration`
    - [ ] `yarn test:ftr`
- [ ] New functionality has been documented.
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

File: src/plugins/data_source/server/client/configure_client.ts [hunk 1]
```diff
@@ -29,53 +25,51 @@ export const configureClient = async (
...
+    const rootClient = getRootClient(dataSource.attributes, config, openSearchClientPoolSetup);
 
-  return getQueryClient(rootClient, dataSource, savedObjects, cryptographyClient);
+    return await getQueryClient(rootClient, dataSource, savedObjects, cryptographyClient);
+  } catch (error: any) {
+    logger.error(
+      `Fail to get data source client for dataSourceId: [${dataSourceId}]. Detail: ${error}`
+    );
+    // Re-throw as DataSourceError
+    throw new DataSourceError('Fail to get data source client: ', 400, error);
```
Comment (noCharger) [inline src/plugins/data_source/server/client/configure_client.ts:38]: The message prefix passed in here seems different from the screen shot. Can we update either?

image

Comment (noCharger) [reply src/plugins/data_source/server/client/configure_client.ts:38]: Also shall we decorate the actual method where throws the error instead, instead of upper stream?

**Review by noCharger — COMMENTED** [review]
Let's also make sure everywhere consume the client can take the Error, for example during the index creation. It would also be helpful if we can add some test cases.

File: src/plugins/data_source/server/client/configure_client.ts (hunk 1 above)
Comment (kristenTian) [inline src/plugins/data_source/server/client/configure_client.ts:38]: not all error will be of 400? what if opensearch js client really failed with 500 issues?

File: src/plugins/data_source/server/lib/error.ts [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+import Boom from '@hapi/boom';
+import { OsdError } from '../../../../../src/plugins/opensearch_dashboards_utils/common';
+
+export class DataSourceError extends OsdError {
+  statusCode: number;
+  body: Record<string, any>;
+  constructor(messagePrefix: string, statusCode: number, e: any) {
```
Comment (kristenTian) [inline src/plugins/data_source/server/lib/error.ts:12]: nit: since e is of any already, maybe just name it explicitly?

File: src/plugins/data_source/server/client/configure_client.ts (hunk 1 above)
Comment (zhongnansu) [reply src/plugins/data_source/server/client/configure_client.ts:38]: `configure_client.ts` has only the logic to create a client, nothing runtime. As far as I know, a Client object can be created with the wrong endpoint, wrong auth, no matter what. The runtime error will happen if caller use that client to make calls, E.g `client.search()`. Then that error is handled by the route handler directly. I don't see anything here that can be a 5xx

File: src/plugins/index_pattern_management/server/routes/resolve_index.ts [hunk 3]
```diff
@@ -60,15 +60,26 @@ export function registerResolveIndexRoute(router: IRouter): void {
...
+        try {
+          const result = await (
+            await context.dataSource.opensearch.getClient(dataSourceId)
+          ).indices.resolveIndex({
+            name: encodeURIComponent(req.params.query),
+            expand_wildcards: req.query.expand_wildcards,
+          });
+          return res.ok({ body: result.body });
+        } catch (err: any) {
+          return res.customError({
```
Comment (kristenTian) [inline src/plugins/index_pattern_management/server/routes/resolve_index.ts:72]: is this conversion needed vs directly throw err?

File: src/plugins/data_source/server/client/configure_client.ts (hunk 1 above)
Comment (kristenTian) [reply src/plugins/data_source/server/client/configure_client.ts:38]: what if the get saveobject call failed?

File: src/plugins/index_pattern_management/server/routes/resolve_index.ts (hunk 3 above)
Comment (zhongnansu) [reply src/plugins/index_pattern_management/server/routes/resolve_index.ts:72]: directly throw error will cause 500

File: src/plugins/data_source/server/client/configure_client.ts (hunk 1 above)
Comment (zhongnansu) [reply src/plugins/data_source/server/client/configure_client.ts:38]: then it creates a hapi/Boom error object, that's why you see in `DataSourceError` I add a conversion. You can take another look at the issue 2210 with the analysis, that why route handler throw 500

File: src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/get_indices.ts [hunk 4]
```diff
@@ -199,7 +199,7 @@ export async function getIndices({
     pattern,
     showAllIndices,
     dataSourceId,
-  }).catch(() => []);
+  });
```
[the remark this answers is not in the document]
Comment (zhongnansu) [reply src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/get_indices.ts:202]: for the UI error pop-up to show

File: src/plugins/index_pattern_management/server/routes/resolve_index.ts (hunk 3 above)
Comment (zhongnansu) [reply src/plugins/index_pattern_management/server/routes/resolve_index.ts:72]: @zengyan-amazon 
Because of `router.ts` will convert any error that's not a Client 401, to internal server error
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/c18736a07388d600a8b23561e1291495a081acb4/src/core/server/http/router/router.ts#L291-L303

Actually I am thinking I should add another `if..else` to the `router.ts` for data source errors, and cast it to a 400

Comment (zhongnansu) [reply src/plugins/index_pattern_management/server/routes/resolve_index.ts:72]: that will also apply all the places that consumes the client, but not having the error handling logic, fyi @noCharger

File: src/plugins/data_source/server/client/configure_client.ts (hunk 1 above)
Comment (zhongnansu) [reply src/plugins/data_source/server/client/configure_client.ts]: added 1 line to print log on server side

File: src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/get_indices.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (zhongnansu) [reply src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/get_indices.ts]: I added back. I think all UI pop-ups will be resolved in another task.

**Review by noCharger — APPROVED** [review]
@zhongnansu  Let's add test coverage

**Review by zengyan-amazon — APPROVED** [review]

**Comment by zhongnansu** [comment]
> @zhongnansu Let's add test coverage

added some UT. Merging the PR
