### PR TITLE
fix(Tooltip): Fixes tooltip when split series charts are used

### LINKED ISSUE #1262: [BUG]  split title missing on tooltop
**Describe the bug**

split title missing on tooltop.
opensearch version is 1.2.0.

It reported on elastic kibana.
https://github.com/elastic/kibana/pull/41708

Already fixed on latest kibana version.

Do we have any plan to fix it ?

Thanks
image

### PR DESCRIPTION
**Pull request by ashwin-pc**
Signed-off-by: Ashwin Pc <ashwinpc@amazon.com>

### Description
On split series charts, the y axis label is incorrect. This change uses the value from the raw table data to correctly assign the value
 
### Issues Resolved
#1262 
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
    - [x] `yarn test:jest`
    - [x] `yarn test:jest_integration`
    - [x] `yarn test:ftr`
- [ ] New functionality has been documented.
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

File: src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.js [hunk 1]
```diff
@@ -55,7 +56,16 @@ export function pointSeriesTooltipFormatter() {
...
     if (datum.y !== null && datum.y !== undefined) {
       const value = datum.yScale ? datum.yScale * datum.y : datum.y;
-      addDetail(currentSeries.label, currentSeries.yAxisFormatter(value));
+      let label = currentSeries.label;
+
+      // For stacked charts the y axis data is only available in the raw table
+      const tableColumns = get(datum, 'yRaw.table.columns');
+      if (tableColumns && tableColumns.length > 2) {
+        const yColumn = datum.yRaw && datum.yRaw.column ? tableColumns[datum.yRaw.column] : {};
+        console.log(tableColumns, datum.yRaw.column);
```
Comment (kavilla) [inline src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.js:65]: boo

Comment (kavilla) [inline src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.js:65]: boo

File: src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.js [hunk 2]
```diff
@@ -55,7 +56,15 @@ export function pointSeriesTooltipFormatter() {
 
     if (datum.y !== null && datum.y !== undefined) {
       const value = datum.yScale ? datum.yScale * datum.y : datum.y;
-      addDetail(currentSeries.label, currentSeries.yAxisFormatter(value));
+      let label = currentSeries.label;
```
Comment (ananzh) [inline src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.js:59]: seems data.yAxisLabel will give the label directly?
is there a specific reason to use datum?

```
data: 
{xAxisOrderedValues: Array(5), xAxisFormat: {…}, xAxisLabel: 'machine.os.keyword: Descending', yAxisFormat: {…}, yAxisLabel: 'Count', …}
hits: 25
series: (15) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
xAxisFormat: {id: 'terms', params: {…}}
xAxisFormatter: val => xConverter.convert(val)
xAxisLabel: "machine.os.keyword: Descending"
xAxisOrderedValues: (5) ['win xp', 'osx', 'win 7', 'win 8', 'ios']
yAxisFormat: {id: 'number'}
yAxisFormatter: val => yConverter.convert(val)
yAxisLabel: "Count"
zAxisFormat: {id: 'terms', params: {…}}
zAxisFormatter: val => zConverter.convert(val)
zAxisLabel: ""
[[Prototype]]: Object
```

File: src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.js [hunk 3]
```diff
@@ -55,7 +56,15 @@ export function pointSeriesTooltipFormatter() {
...
+
+      // For stacked charts the y axis data is only available in the raw table
+      const tableColumns = get(datum, 'yRaw.table.columns');
+      if (tableColumns && tableColumns.length > 2) {
+        const yColumn = datum.yRaw && datum.yRaw.column ? tableColumns[datum.yRaw.column] : {};
```
Comment (ananzh) [inline src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.js:64]: tableColumns is get from `get(datum, 'yRaw.table.columns')`, so the if clause `if(tableColumns && ...)` already test the existence of `datum.yRaw.table.columns`.

`datum.yRaw.table.columns` exists then `datum.yRaw` should exist right?
so can `yColumn` just be `yColumn = datum.yRaw.column ? tableColumns[datum.yRaw.column] : {};`

**Review by ananzh — COMMENTED** [review]
some comments. Thanks Ashwin.

File: src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.js (hunk 2 above)
Comment (ashwin-pc) [reply src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.js:59]: Unfortunately, when we have multiple fields on the y axis, the `yAxisLabel` is incorrectly set. The only way we have to correctly get the label then is from the `yRaw` value. Thats why i check in the next few lines to check to see if we have more than one y-axis field before using the `yRaw` value instead of the default label. I've added the comment below to call this out as well.

File: src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.js (hunk 3 above)
Comment (ashwin-pc) [reply src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.js:64]: Good callout. I didn't notice the duplicate check. I think i was working as if this was a typescript file which would definitely complain if i ignored that check. Will remove it.

File: src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.js [hunk 4]
```diff
@@ -53,7 +54,15 @@ export function pointSeriesTooltipFormatter() {
 
     if (datum.y !== null && datum.y !== undefined) {
       const value = datum.yScale ? datum.yScale * datum.y : datum.y;
-      addDetail(currentSeries.label, currentSeries.yAxisFormatter(value));
+      let label = currentSeries.label;
+
+      // For stacked charts the y axis data is only available in the raw table
+      const tableColumns = get(datum, 'yRaw.table.columns');
```
Comment (AMoo-Miki) [inline src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.js:60]: I would prefer `datum?.yRaw?.table?.columns` to loading `lodash` just for this.

**Review by AMoo-Miki — DISMISSED** [review]

File: src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.js (hunk 4 above)
Comment (ashwin-pc) [reply src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.js:60]: Good callout. Still need wrap my head around the fact that we now have opt chaining in Javascript. I'll leave this in for now unless there is another iteration needed since this is mostly just a stylistic change.

**Review by boktorbb-amzn — DISMISSED** [review]
Looks good

File: src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.js (hunk 4 above)
Comment (tmarkley) [reply src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.js:60]: Agreed on this. Are we planning on changing this or no because there are no other changes?

**Review by kavilla — APPROVED** [review]
LGTM! It solves the problem but @AMoo-Miki does raise a good  point about loading lodash.

**Review by kavilla — APPROVED** [review]
LGTM, thanks!

**Review by tmarkley — APPROVED** [review]
Thanks Ashwin!

**Comment by tmarkley** [comment]
@ashwin-pc which version(s) are we targeting? Feel free to add the labels!
