### PR TITLE
Fix wording and duplicate code in embeddable example plugin

### LINKED ISSUE #3906: Confusing wording for embeddable example plugin
**Describe the bug**

The description for the list container embeddable in the embeddable example plugin is confusing and does not provide a clear and helpful description of the functionality, especially the `checkMatching` feature.

The paragraph can be reworded to be more helpful.
Screenshot 2023-04-20 at 3 53 35 PM

### PR DESCRIPTION
**Pull request by abbyhu2000**
### Description

Add more description to the list container embeddable in the embeddable example plugin. Also remove a line of duplicate code.

### Issues Resolved

resolve #3906 

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

File: examples/embeddable_examples/public/searchable_list_container/searchable_list_container_component.tsx [hunk 1]
```diff
@@ -82,7 +82,6 @@ export class SearchableListContainerComponentInner extends Component<Props, Stat
       const output = props.embeddable.getChild(id).getOutput();
       hasMatch[id] = hasHasMatchOutput(output) && output.hasMatch;
     });
-    props.embeddable.getChildIds().forEach((id) => (checked[id] = false));
```
Comment (abbyhu2000) [inline examples/embeddable_examples/public/searchable_list_container/searchable_list_container_component.tsx:85]: This line is a duplicate of line 81

**Review by manasvinibs — APPROVED** [review]

**Review by zhongnansu — APPROVED** [review]
lgtm
