### PR TITLE
[Discover] Decouple `data$` updates to prevent rows clearing on hook re-render

### LINKED ISSUE #8552: [BUG] Discover runs query again when adding or removing selected fields
**Describe the bug**

In Discover, adding or removing a field from "Selected fields" on the left side bar will trigger the query to run again. It's an acceptable behavior but doesn't work well for async queries which are slow to run.

**To Reproduce**
1. Go to https://playground.opensearch.org/app/data-explorer/discover#
2. query anything
3. open browser network tab, clear
4. on the left, drag a field to "Selected fields"
5. See two APIs triggered, the first one calls `PUT /api/saved_objects/index-pattern/<id>` and received 403. There is also a `POST /internal/search/opensearch-with-long-numerals` which reruns the query 
image

**Expected behavior**
Do not rerun the query unless necessary

**OpenSearch Version**
playground

**Dashboards Version**
playground

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

### PR DESCRIPTION
**Pull request by joshuali925**
### Description

While https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8552 is fixed by not letting query automatically run again, updating selected field still clears all rows in discover. This happens because any re-render to hook `useSearch` will clear `data$` by creating a new observable.

This PR fixes it by decoupling update logic based on dependencies.

### Issues Resolved

#8552 

## Screenshot

No UI change

## Testing the changes

i don't see UT for `useSearch`, @LDrago27 could you take a look if they will break anything?

## Changelog

- fix: decouple data$ updates to prevent rows clearing on hook re-render

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by ashwin-pc** [comment]
@joshuali925 can you add a UT atleast for your part of the change?

File: src/plugins/discover/public/application/view_components/utils/use_search.ts [hunk 1]
```diff
@@ -143,8 +144,45 @@ export const useSearch = (services: DiscoverViewServices) => {
...
+
+  useEffect(() => {
+    data$.next({
+      ...data$.value,
+      status:
+        shouldSearchOnPageLoad() && !skipInitialFetch.current
+          ? ResultStatus.LOADING
+          : ResultStatus.UNINITIALIZED,
+    });
+  }, [data$, shouldSearchOnPageLoad, skipInitialFetch]);
```
Comment (sejli) [inline src/plugins/discover/public/application/view_components/utils/use_search.ts:184]: Is there a reason why this is separated into two `useEffect()`'s? If mimicking the original `useMemo()`, could be done in a single update and reduce the number of `useEffects()`.

Comment (joshuali925) [reply src/plugins/discover/public/application/view_components/utils/use_search.ts:184]: startTime updates should only update `queryStatus.startTime` and not reset `status`. it's the bug this PR is trying to fix, we should decouple queryStatus and status updates

**Review by virajsanghvi — APPROVED** [review]

**Review by sejli — APPROVED** [review]
