### PR TITLE
Fix open link in new tab from table field

### LINKED ISSUE #3500: [BUG] open in a new tab broken in 2.5.0
**Describe the bug**

Opensearch version 2.5.0 (was working in previous versions)

Go to “Stack Management”, then “index patterns”, select an index pattern and edit a field to format it as a URL. The option “Open in a new tab” doesn’t make the links open in a new tab:
Screenshot 2023-02-24 at 7 24 05 PM

The link opens correctly but in the same window and tab whether this option is turned on or off.

This option worked in a previous version (not sure which version that was)

**To Reproduce**
Go to “Stack Management”, then “index patterns”, select an index pattern and edit a field to format it as a URL. The option “Open in a new tab” doesn’t make the links open in a new tab.

**Expected behavior**
The link should open in a new window.

**OpenSearch Version**
2.5.0

**Dashboards Version**
2.5.0

**Host/Environment (please complete the following information):**
 - OS: docker version on ubuntu host
 - Browser: chrome and safari

### PR DESCRIPTION
**Pull request by sejli**
### Description

Building off #9787

Since the `table_vis_cell.tsx` component was rewritten to `table_vis_dynamic_table.tsx`, this PR updates it such that the `dompurify` hooks are in the correct component. For 2.19, which does not have the rewritten `table_vis_dynamic_table.tsx`, #11456 was opened to maintain the same behavior for opening links in a new tab.

### Issues Resolved

#3500

## Changelog

- fix: Fix open link in new tab from table field

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

File: src/plugins/vis_type_table/public/components/table_vis_cell.tsx [hunk 1]
```diff
@@ -23,6 +23,17 @@ export const getTableVisCellValue = (
...
+    if (event.attrName === 'target') {
+      event.forceKeepAttr = true;
+    }
+  });
+
+  dompurify.addHook('afterSanitizeElements', (node) => {
+    if (node instanceof Element && node.tagName?.toUpperCase() === 'A') {
+      node.setAttribute('rel', 'noopener noreferrer');
+    }
+  });
```
Comment (angle943) [inline src/plugins/vis_type_table/public/components/table_vis_cell.tsx]: is this safe? The only thing this is checking for is that the node is an anchor tag. wouldn't this run if `afterSanitizeElements` ran for a completely different, unrelated anchor tag, say like an internal nav link (now why would we run dompurify on that who knows)

is it possible to be more specific then just targetting all anchor tags?

Comment (Maosaic) [inline src/plugins/vis_type_table/public/components/table_vis_cell.tsx]: AI suggesting to move these to module scope like `able_vis_dynamic_table.tsx`, any reason doing it differently here?

```
dompurify.addHook() calls are placed inside the getTableVisCellValue render function body rather than at module scope. This causes new hooks to be registered on every single cell render, leading to unbounded hook accumulation. Over time this produces unpredictable sanitization behavior as stacked duplicate hooks all execute, and could degrade or circumvent the intended sanitization logic. Unlike the parallel change in table_vis_dynamic_table.tsx (which correctly places the same hooks at module level), this placement is anomalous and warrants investigation.
```

Comment (sejli) [reply src/plugins/vis_type_table/public/components/table_vis_cell.tsx]: Just removed this, it's not needed since `table_vis_cell.tsx` is no longer used post rewrite.

Comment (sejli) [reply src/plugins/vis_type_table/public/components/table_vis_cell.tsx]: Reverted the original changes since that component is no longer used.
