### PR TITLE
[D&D] Fix: Topnav updates aggregation parameters

### LINKED ISSUE #1903: [D&D] Fix support for query, filter and timerange
Currently query, filter and timerange settings applied in the top nav do not affect the visualization. Fix this to correctly aggregate the data based on these filters. 

- [x] Add support for updating the expression context based on query, filter and timerange
- [x] Updating the ranges should automatically update the viz

### PR DESCRIPTION
**Pull request by ashwin-pc**
### Description
D&D TopNav now works with the visualization. Query, Filters and Time range.
  
### Issues Resolved
#1903 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
    - [ ] `yarn test:jest`
    - [ ] `yarn test:jest_integration`
    - [ ] `yarn test:ftr`
- [ ] New functionality has been documented.
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by AMoo-Miki — APPROVED** [review]

File: src/plugins/wizard/public/application/components/top_nav.tsx [hunk 1]
```diff
@@ -58,10 +58,10 @@ export const TopNav = () => {
         appName={PLUGIN_ID}
         config={config}
         setMenuMountPoint={setHeaderActionMenu}
-        showSearchBar={true}
-        useDefaultBehaviors={true}
-        screenTitle="Test"
```
Comment (joshuarrrr) [inline src/plugins/wizard/public/application/components/top_nav.tsx:63]: Do we still need a defined screen title or does it default to the app name or something?

File: src/plugins/wizard/public/visualizations/metric/to_expression.ts [hunk 2]
```diff
@@ -171,5 +171,5 @@ export const toExpression = async ({ style: styleState, visualization }: MetricR
 
   const ast = buildExpression([opensearchaggs, metricVis]);
 
-  return ast.toString();
+  return `opensearchDashboards | opensearch_dashboards_context | ${ast.toString()}`;
```
Comment (joshuarrrr) [inline src/plugins/wizard/public/visualizations/metric/to_expression.ts:174]: I assume this change is intended, and maybe it's obvious for someone who understands expressions, but an explanatory comment would seem useful.

**Review by joshuarrrr — APPROVED** [review]

File: src/plugins/wizard/public/application/components/workspace.tsx [hunk 3]
```diff
@@ -66,13 +87,13 @@ export const Workspace: FC = ({ children }) => {
       </EuiFlexGroup>
       <EuiPanel className="wizCanvas">
         {expression ? (
-          <ReactExpressionRenderer expression={expression} />
+          <ReactExpressionRenderer expression={expression} searchContext={searchContext} />
```
Comment (ruanyl) [inline src/plugins/wizard/public/application/components/workspace.tsx:90]: `ReactExpressionRenderer` has a prop `reload$`:
```
An observable which can be used to re-run the expression without destroying the component
```
Does it make sense to use that instead of an arbitrary prop `searchContext`?

File: src/plugins/wizard/public/application/components/top_nav.tsx (hunk 1 above)
Comment (ashwin-pc) [reply src/plugins/wizard/public/application/components/top_nav.tsx:63]: it's an optional parameter that can be the title of the visualization but it can be ignored. When ignored the title is OpenSearch Dashboards. We can add it in future when we have the saved object stuff all polished up.

File: src/plugins/wizard/public/visualizations/metric/to_expression.ts (hunk 2 above)
Comment (ashwin-pc) [reply src/plugins/wizard/public/visualizations/metric/to_expression.ts:174]: The `toExpression` function needs some TLC as a whole. I plan on refactoring this when we have more than one viz type. `opensearchDashboards | opensearch_dashboards_context` are the expression functions that get the top nav context and pass it along to the agg function. For now ill leave it as is since this is how the `build_pipeline.ts` does it too. 

I want to abstract away most of this logic into utility functions so that all we have here is some sort of builder function that simply chains the expression function builders.

File: src/plugins/wizard/public/application/components/workspace.tsx (hunk 3 above)
Comment (ashwin-pc) [reply src/plugins/wizard/public/application/components/workspace.tsx:90]: Yeah, for now either the `searchContext` or `expression` will need to change causing a reload anyways. But thanks for calling that out. This will be useful in instances where neither change but you still want to trigger a reload.
