### PR TITLE
Fixes broken app when management is turned off

### LINKED ISSUE #4671: [BUG] `visAugmenter` requiring `savedObjectsManagement` puts other features at jeopardy
**Describe the bug**

A lot of visualizations indicate that they require bundles from `visAugmenter` who requires bundles from `savedObjectsManagement` and that requires the management plugin. If the `management` plugin is disabled everything falls apart.

Ideally, `visAugmenter` should gracefully degrade by not requiring `savedObjectsManagement` and checking if it is available before doing
```
uiActions.addTriggerAction(SAVED_OBJECT_DELETE_TRIGGER, savedObjectDeleteAction);
```

**To Reproduce**
1. Add `management.enabled: false` to the config
2. Restart and access OSD

**Expected behavior**
Everything should work

**OpenSearch Version**
Any

**Dashboards Version**
2.9.0

**Additional context**

#4642

### PR DESCRIPTION
**Pull request by ashwin-pc**
### Description

Then `management.enabled: false` is set in the config, the app now correctly loads without breaking.

### Issues Resolved

fixes #4671

## Testing the changes

set `management.enabled: false` in the config file and startup OSD. All the pages should be working while the management pages are disabled.

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by lezzago — APPROVED** [review]

**Review by kavilla — APPROVED** [review]

File: src/plugins/vis_augmenter/public/ui_actions_bootstrap.ts [hunk 1]
```diff
@@ -71,8 +71,15 @@ export const bootstrapUiActions = (uiActions: UiActionsSetup) => {
...
-  uiActions.addTriggerAction(EXTERNAL_ACTION_TRIGGER, openEventsFlyoutAction);
-  uiActions.addTriggerAction(CONTEXT_MENU_TRIGGER, viewEventsOptionAction);
-  uiActions.addTriggerAction(SAVED_OBJECT_DELETE_TRIGGER, savedObjectDeleteAction);
   uiActions.addTriggerAction(PLUGIN_RESOURCE_DELETE_TRIGGER, pluginResourceDeleteAction);
+  uiActions.addTriggerAction(EXTERNAL_ACTION_TRIGGER, openEventsFlyoutAction);
+
+  // These triggers are registered by other plugins. If they are disabled can throw an error.
+  try {
+    uiActions.addTriggerAction(CONTEXT_MENU_TRIGGER, viewEventsOptionAction);
+    uiActions.addTriggerAction(SAVED_OBJECT_DELETE_TRIGGER, savedObjectDeleteAction);
```
Comment (AMoo-Miki) [inline src/plugins/vis_augmenter/public/ui_actions_bootstrap.ts:80]: wouldn't it be safer to wrap them individually? That way, a failure, due to one plugin being disabled, will not prevent other listeners from being added.

File: src/plugins/vis_augmenter/public/ui_actions_bootstrap.ts [hunk 2]
```diff
@@ -71,8 +71,15 @@ export const bootstrapUiActions = (uiActions: UiActionsSetup) => {
   uiActions.registerTrigger(externalActionTrigger);
   uiActions.registerTrigger(pluginResourceDeleteTrigger);
 
-  uiActions.addTriggerAction(EXTERNAL_ACTION_TRIGGER, openEventsFlyoutAction);
-  uiActions.addTriggerAction(CONTEXT_MENU_TRIGGER, viewEventsOptionAction);
-  uiActions.addTriggerAction(SAVED_OBJECT_DELETE_TRIGGER, savedObjectDeleteAction);
   uiActions.addTriggerAction(PLUGIN_RESOURCE_DELETE_TRIGGER, pluginResourceDeleteAction);
+  uiActions.addTriggerAction(EXTERNAL_ACTION_TRIGGER, openEventsFlyoutAction);
+
+  // These triggers are registered by other plugins. If they are disabled can throw an error.
```
Comment (joshuarrrr) [inline src/plugins/vis_augmenter/public/ui_actions_bootstrap.ts:77]:
```suggestion
  // These triggers are registered by other plugins. If they are disabled, adding an action can throw an error.
```

File: src/plugins/vis_augmenter/public/ui_actions_bootstrap.ts (hunk 1 above)
Comment (joshuarrrr) [reply src/plugins/vis_augmenter/public/ui_actions_bootstrap.ts:80]: I think I agree, but this may be fine for the current state of the augmenter feature. @ohltyler @lezzago , what's the intended behavior in the case were only management is disabled?

**Review by joshuarrrr — APPROVED** [review]

File: src/plugins/vis_augmenter/public/ui_actions_bootstrap.ts (hunk 1 above)
Comment (ashwin-pc) [reply src/plugins/vis_augmenter/public/ui_actions_bootstrap.ts:80]: Yeah with the current behaviour this is fine. The context menu trigger comes from the embeddables plugin which is not something we disable (Dashboards would not work without it). So in theory the only real action that cannot be registered is the savedObject Management trigger, which is already the second action in the try block.
