### PR TITLE
[Windows] Facilitate building of OSD and plugins

### LINKED ISSUE #1492: [BUG] [Help me,Thanks]  run yarn build-platform appear "EINVAL: invalid argument"  errors on windows
**Describe the bug**

in git bash run yarn build-platform appear "EINVAL: invalid argument" error

**To Reproduce**
1. yarn build-platform 
2. See error

**Expected behavior**
build successful

**OpenSearch Version**
v1.2.0

**Dashboards Version**
v1.2.0

**Plugins**
none

**Screenshots**

Snipaste_2022-04-25_16-51-14

**Host/Environment (please complete the following information):**
 - OS: windows10
 - Browser and version: chrome
 - node.js: v10.24.1
 - 
**Additional context**

I just pulled the code from GitHub, installed the dependency, and then implemented the package without making any code changes. Such an error occurred

I tried to solve it. It's the FS of node For questions about utimes, refer to the link: [https://github.com/nodejs/node/issues/5561](https://github.com/nodejs/node/issues/5561)

### LINKED ISSUE #2603: Getting error while bootstrapping opensearch dashboard in Windows
**Describe the bug**

While trying to setup the OpenSearch dashboard in my windows machine following the guide.

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md

when I try to run:
 $ yarn osd bootstrap 

I get the following error
image

**To Reproduce**

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

### PR DESCRIPTION
**Pull request by AMoo-Miki**
### Description
* Enables building and running OSD on Windows
* Enabled building and installing plugins on Windows
 
### Issues Resolved
Fixes #2603
Fixed #1492
 
### Check List
- [ ] All tests pass
  - [X] `yarn test:jest`
  - [x] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [X] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by AMoo-Miki** [comment]
> Awesome!
> 
> do we solve this issue: #1310

Not yet. That's the next thing on my list.

File: scripts/remove.js [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+  .map((item) => path.resolve(item));
+
+if (toDeletes.length === 0) {
+  console.warn('Nothing to delete');
+  process.exit(0);
+}
+
+(async () => {
+  const deletedPaths = await del(toDeletes);
+  if (deletedPaths === 9) {
```
Comment (ashwin-pc) [inline scripts/remove.js:26]: Can we add a comment here as to why we check for 9?

File: src/cli_plugin/install/settings.test.js [hunk 2]
```diff
@@ -137,7 +137,7 @@ describe('parse function', function () {
     `);
   });
 
-  it('should throw when on a non-Linux platform', function () {
+  it('produces expected results on Windows', function () {
```
Comment (ashwin-pc) [inline src/cli_plugin/install/settings.test.js:140]: Nice how you changed this error test into a success test ;)

File: scripts/remove.js (hunk 1 above)
Comment (ananzh) [inline scripts/remove.js:26]: Do we still need this if clause if process exit at #line21? why do we need to check again?

**Review by ashwin-pc — APPROVED** [review]
Just one question about the `osd:watch` script, but not blocking on that.

File: packages/osd-optimizer/src/common/bundle.test.ts [hunk 3]
```diff
@@ -88,13 +89,16 @@ it('provides the module count from the cache', () => {
 
 it('parses bundles from JSON specs', () => {
   const bundles = parseBundles(JSON.stringify([SPEC]));
+  let expectedCachePath = resolve('/foo/bar/target/.osd-optimizer-cache');
+  // Cannot use `standardize` from `@osd/util` due to mocking of fs
+  if (process?.platform === 'win32') expectedCachePath = expectedCachePath.replace(/\\/g, '\\\\');
```
Comment (ananzh) [inline packages/osd-optimizer/src/common/bundle.test.ts:94]: do we need a `?` here?

File: packages/osd-plugin-generator/src/integration_tests/generate_plugin.test.ts [hunk 4]
```diff
@@ -32,13 +32,17 @@ import Path from 'path';
...
 import globby from 'globby';
 
-const GENERATED_DIR = Path.resolve(REPO_ROOT, `plugins`);
+// Has to be a posix reference because it is used to generate glob patterns
+const GENERATED_DIR = standardize(Path.resolve(REPO_ROOT, `plugins`), true);
 
-expect.addSnapshotSerializer(createAbsolutePathSerializer());
+expect.addSnapshotSerializer(
+  createAbsolutePathSerializer(
+    process?.platform === 'win32' ? standardize(REPO_ROOT, true) : REPO_ROOT
```
Comment (ananzh) [inline packages/osd-plugin-generator/src/integration_tests/generate_plugin.test.ts:43]: same question. can process be undefined?

File: src/core/server/plugins/plugin.ts [hunk 5]
```diff
@@ -45,6 +45,8 @@ import {
 } from './types';
 import { CoreSetup, CoreStart } from '..';
 
+const { join } = posix;
```
Comment (ananzh) [inline src/core/server/plugins/plugin.ts:48]: why not import join directly?

File: scripts/remove.js (hunk 1 above)
Comment (AMoo-Miki) [reply scripts/remove.js:26]: Good catch! That was supposed to be `0` but my sleepless eyes saw it as zero!

File: packages/osd-opensearch-archiver/package.json [hunk 6]
```diff
@@ -7,8 +7,8 @@
     "devOnly": true
   },
   "scripts": {
-    "osd:bootstrap": "rm -rf target && tsc",
-    "osd:watch": "rm -rf target && tsc --watch"
+    "osd:bootstrap": "node ../../scripts/remove.js target && tsc",
+    "osd:watch": "node ../../scripts/remove.js && tsc --watch"
```
[the remark this answers is not in the document]
Comment (AMoo-Miki) [reply packages/osd-opensearch-archiver/package.json:11]: Thanks

File: scripts/remove.js (hunk 1 above)
Comment (AMoo-Miki) [reply scripts/remove.js:26]: I changed the message.

`toDeletes` is the requested list and `deletedPaths` is the list of the ones that actually got deleted.

File: packages/osd-optimizer/src/common/bundle.test.ts (hunk 3 above)
Comment (AMoo-Miki) [reply packages/osd-optimizer/src/common/bundle.test.ts:94]: I figured it is common so it could be called in unit tests as well as integration tests; just being safe.

File: packages/osd-plugin-generator/src/integration_tests/generate_plugin.test.ts (hunk 4 above)
Comment (AMoo-Miki) [reply packages/osd-plugin-generator/src/integration_tests/generate_plugin.test.ts:43]: Same :D

File: src/core/server/plugins/plugin.ts (hunk 5 above)
Comment (AMoo-Miki) [reply src/core/server/plugins/plugin.ts:48]: Even though the syntax looks like destructuring, they are in fact named imports. Hence something like `import { posix: { join } }` wouldn't work.

**Review by ashwin-pc — APPROVED** [review]

**Review by ananzh — APPROVED** [review]
