### PR TITLE
[Bug] fix TSVB y-axis

### LINKED ISSUE #1873: [BUG] TSVB y-axis missing
**Describe the bug**

All y-axis in the TSVB visualizations are missing.

**To Reproduce**
1. Update to version 2.0.1 or 2.1.0 
2. Create a TSVB

**Expected behavior**
Y-axis should be visible as it was before

**OpenSearch Version**
2.0.1; 2.1.0

**Dashboards Version**
2.0.1; 2.1.0

**Plugins**

Default

### PR DESCRIPTION
**Pull request by AbhishekReddy1127**
Signed-off-by: AbhishekReddy1127 <nallamsa@amazon.com>

### Description
Fixed the TSVB y-axis.
 
### Issues Resolved
#1873 
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
    - [x] `yarn test:jest`
    - [x] `yarn test:jest_integration`
    - [x] `yarn test:ftr`
- [ ] New functionality has been documented.
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by joshuarrrr — COMMENTED** [review]
@AbhishekReddy1127 Great find!

Usually the hard work in a bug fix like this is the sleuthing that it takes to understand the what caused the buggy behavior (and, in a regression like this, when/what introduced it). 

Can you add an explanation of the fix to the issue description (and commit body)? That will help future devs understand why/how this fixed the bug.

In addition, for a UI issue, it's useful to have a screenshot or animation in the description that shows that it fixes the bug. Are there any tests you have found that should be updated to prevent a similar regression in the future?

**Comment by kavilla** [comment]
> @AbhishekReddy1127 Great find!
> 
> Usually the hard work in a bug fix like this is the sleuthing that it takes to understand the what caused the buggy behavior (and, in a regression like this, when/what introduced it).
> 
> Can you add an explanation of the fix to the issue description (and commit body)? That will help future devs understand why/how this fixed the bug.
> 
> In addition, for a UI issue, it's useful to have a screenshot or animation in the description that shows that it fixes the bug. Are there any tests you have found that should be updated to prevent a similar regression in the future?

+1, yes thanks @AbhishekReddy1127 for getting this. But will help will why removing this was the bug and also ensuring we don't have any regressions.

**Review by ananzh — APPROVED** [review]

File: src/plugins/vis_type_timeseries/public/application/components/vis_types/timeseries/vis.js [hunk 1]
```diff
@@ -212,7 +212,6 @@ export class TimeseriesVisualization extends Component {
           seriesDataRow.groupId = groupId;
           seriesDataRow.yScaleType = yScaleType;
           seriesDataRow.hideInLegend = Boolean(seriesGroup.hide_in_legend);
-          seriesDataRow.useDefaultGroupDomain = !isCustomDomain;
```
Comment (mihirsoni) [inline src/plugins/vis_type_timeseries/public/application/components/vis_types/timeseries/vis.js:215]: Could we post the behavior, for before / after change to ensure we are getting expected behavior ?

Comment (AbhishekReddy1127) [reply src/plugins/vis_type_timeseries/public/application/components/vis_types/timeseries/vis.js:215]: @kavilla @mihirsoni @joshuarrrr @ananzh 
**This is how the Y-axis was looking due to the bug.**
Screen Shot 2022-08-09 at 11 15 22 AM

But in my investigation I came to know that, this was happening because of a prop `useDefaultGroupDomain`. Actually this prop was introduced into the elastic charts to allow clustering for the multiple series which will share a common Y domain i.e for example the stacked and non- stacked bars will have the same Y common domain/axis. As per the elastic/charts whenever the `useDefaultGroupDomain` is set to true, it will force to group the series/visualiations groupId's to a  default group domain. But, TSVB is not a shared Y domain. So, I felt `useDefaultGroupDomain` may not be the right prop for TSVB. 

Either we can remove the line 215 as I did above or by setting the `useDefaultGroupDomain` to **false** is also solving this issue.

**After removing the line, the output is looking like:**
Screen Shot 2022-08-09 at 11 34 45 AM

**or, after setting the `useDefaultGroupDomain` to false**
Screen Shot 2022-08-09 at 11 36 50 AM

As,@joshuarrrr asked about the tests, i could think of like to verify whether the `useDefaultGroupDomain` is set to false so that TSVB will work as expected.
This is what I have with me until now. Please correct me if i am wrong anywhere.

**Comment by AMoo-Miki** [comment]
From what I see in the code:
```
const groupId = hasSeparateAxis || isStackedWithinSeries ? seriesGroup.id : mainAxisGroupId;
```
where
```
const mainAxisGroupId = yAxisIdGenerator('main_group');
```
... which indicates that the global default `groupId` is not used by TSVB. Hence, TSVB should have not been using `useDefaultGroupDomain` ever.

**Review by AMoo-Miki — APPROVED** [review]
