### PR TITLE
Fix: copy essential property to generated request

### LINKED ISSUE #9673: [BUG] `createRequest` is not extend the request property correctly
**Describe the bug**

https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9641 upgrade some dependencies but forget to extend the request correctly, making request.path always '/'.

Image

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

### PR DESCRIPTION
**Pull request by SuZhou-Joe**
### Description

Extend essential property to generated request

### Issues Resolved

fixes #9673

## Changelog

- fix: copy essential property to generated request

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by zhongnansu — DISMISSED** [review]

**Review by zhongnansu — APPROVED** [review]

File: src/plugins/data_source/server/legacy/http_aws_es/connector.js [hunk 1]
```diff
@@ -98,6 +98,9 @@ class HttpAmazonESConnector extends HttpConnector {
       hostname: this.endpoint.hostname,
     });
 
+    // copy across params
+    Object.assign(request, reqParams);
+
```
Comment (Hailong-am) [inline src/plugins/data_source/server/legacy/http_aws_es/connector.js:103]: will reqParams contains `endpoint` or `hostname`?

Comment (SuZhou-Joe) [reply src/plugins/data_source/server/legacy/http_aws_es/connector.js:103]: Not likely, reqParams is supposed to contain only query / body / path, and actually it is a existing logic in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9641/files#diff-1a4e548980eeca5855fdea8b28f692f1becf52b524a6bfe40573c0d6aed29ebcL111-L112 . The previous PR forget to add it back while upgrading aws-sdk.

**Comment by cwperks** [comment]
Thank you @SuZhou-Joe! These changes look good to me!

**Review by cwperks — APPROVED** [review]
