### PR TITLE
Fix broken link in the Overview page

### LINKED ISSUE #193: [BUG] Sample data path from Overview page is broken
When navigating from the home page to the sample data page using the 'Try our sample data' link, it routes properly but if you use the same link from the overview page it breaks and gives an empty page. 

This is likely because the code is currently just appending the `/tutorial_directory/sampleData` path to the current path the user is on. When navigating from overview, I see the path as `/opensearch_dashboards_overview#/tutorial_directory/sampleData` but it should always use `/home#/tutorial_directory/sampleData`

### PR DESCRIPTION
**Pull request by vchrombie**
### Description

The 'Try our sample data' link in the opensearch dashboards overview page is broken. It has to be pointed to the path `/app/home#/tutorial_directory/sampleData`. This commit fixes this bug. The snapshots are updated accordingly.
 
### Issues Resolved

Fixes #193 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

File: src/plugins/opensearch_dashboards_overview/public/components/add_data/add_data.tsx [hunk 1]
```diff
@@ -72,7 +72,7 @@ export const AddData: FC<Props> = ({ addBasePath, features }) => {
             <EuiButtonEmpty
               className="osdOverviewDataAdd__actionButton"
               flush="left"
-              href={addBasePath('#/tutorial_directory/sampleData')}
+              href="/app/home#/tutorial_directory/sampleData"
```
Comment (mihirsoni) [inline src/plugins/opensearch_dashboards_overview/public/components/add_data/add_data.tsx:75]: Any reason, why the `addBasePath` is not working expected ?

**Review by mihirsoni — COMMENTED** [review]
Thanks @vchrombie for the PR, I have few small comments.

File: src/plugins/opensearch_dashboards_overview/public/components/add_data/add_data.tsx (hunk 1 above)
Comment (vchrombie) [reply src/plugins/opensearch_dashboards_overview/public/components/add_data/add_data.tsx:75]: I'm not sure, but I will check it once and get back to you.
Thanks for the review.

Comment (vchrombie) [reply src/plugins/opensearch_dashboards_overview/public/components/add_data/add_data.tsx:75]: Hi @mihirsoni 
From what I understand, `addBasePath` redirects to `localhost:5601`, so the target href has to be updated. We can add `/app/home` to complete the existing href. WDYT?
```
-              href={addBasePath('#/tutorial_directory/sampleData')} 
+              href={addBasePath('/app/home#/tutorial_directory/sampleData/')}
```

[(opensearch_dashboards_overview) getting_started.tsx#L122](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/opensearch_dashboards_overview/public/components/getting_started/getting_started.tsx#L122)
[(opensearch_dashboards_react) overview_page_header.tsx#L109](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/opensearch_dashboards_react/public/overview_page/overview_page_header/overview_page_header.tsx#L109)

**Review by boktorbb-amzn — CHANGES_REQUESTED** [review]
After pulling the PR down, I notice that the link works now but it doesn't seamlessly route to the sample data path like on the home screen but actually reloads the whole dashboards app. While this works, it isn't fully the experience we want. Could you take a look there?

**Comment by vchrombie** [comment]
Hi @amazon-auto, thanks for the review.

> After pulling the PR down, I notice that the link works now but it doesn't seamlessly route to the sample data path like on the home screen but actually reloads the whole dashboards app. While this works, it isn't fully the experience we want. Could you take a look there?

Nice catch, you are right. I could fix the issue and updated the PR too. Can you look at this again?

**Review by boktorbb-amzn — APPROVED** [review]
The link is redirecting properly now. Looks good to me and thank you for your contribution!

**Review by kavilla — APPROVED** [review]
LGTM! One integ test failing but unrelated to this and currently being fixed. Otherwise unit and functional tests are passing.

Thank you!
