### PR TITLE
[CCI] Fix type errors in i18n

### LINKED ISSUE #3027: Fix type errors in i18n
Task for https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1660

(inherited from previous project)

```
$tsc --noEmit
...

src/dev/i18n/utils/verify_icu_message.ts:43:15 - error TS2351: This expression is not constructable.
  Type 'Error' has no construct signatures.

43     throw new parser.SyntaxError(
                 ~~~~~~~~~~~~~~~~~~

src/dev/i18n/utils/verify_icu_message.ts:54:19 - error TS2351: This expression is not constructable.
  Type 'Error' has no construct signatures.

54         throw new parser.SyntaxError(
                     ~~~~~~~~~~~~~~~~~~

src/dev/run_i18n_check.ts:92:23 - error TS2322: Type 'Listr<{ reporter: ErrorReporter; }>' is not assignable to type 'void | ListrTaskResult<{ config: I18nConfig; }>'.
  Type 'Listr<{ reporter: ErrorReporter; }>' is not assignable to type 'Listr<{ config: I18nConfig; }>'.
    Types of property 'tasks' are incompatible.
      Type 'readonly ListrTaskWrapper<{ reporter: ErrorReporter; }>[]' is not assignable to type 'readonly ListrTaskWrapper<{ config: I18nConfig; }>[]'.
        Type 'ListrTaskWrapper<{ reporter: ErrorReporter; }>' is not assignable to type 'ListrTaskWrapper<{ config: I18nConfig; }>'.
          Type '{ reporter: ErrorReporter; }' is not assignable to type '{ config: I18nConfig; }'.

92           task: () => new Listr(checkConfigs(includeConfig), { exitOnError: true }),
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@types/listr/index.d.ts:33:15
    33         task: (ctx: Ctx, task: ListrTaskWrapper<Ctx>) => void | ListrTaskResult<Ctx>;
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from the return type of this signature.
  src/dev/run_i18n_check.ts:92:17
    92           task: () => new Listr(checkConfigs(includeConfig), { exitOnError: true }),
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Did you mean to mark this function as 'async'?

src/dev/run_i18n_check.ts:96:23 - error TS2322: Type 'Listr<{ reporter: ErrorReporter; config?: I18nConfig | undefined; }>' is not assignable to type 'void | ListrTaskResult<{ config: I18nConfig; }>'.
  Type 'Listr<{ reporter: ErrorReporter; config?: I18nConfig | undefined; }>' is not assignable to type 'Listr<{ config: I18nConfig; }>'.
    Types of property 'tasks' are incompatible.
      Type 'readonly ListrTaskWrapper<{ reporter: ErrorReporter; config?: I18nConfig | undefined; }>[]' is not assignable to type 'readonly ListrTaskWrapper<{ config: I18nConfig; }>[]'.
        Type 'ListrTaskWrapper<{ reporter: ErrorReporter; config?: I18nConfig | undefined; }>' is not assignable to type 'ListrTaskWrapper<{ config: I18nConfig; }>'.
          Type '{ reporter: ErrorReporter; config?: I18nConfig | undefined; }' is not assignable to type '{ config: I18nConfig; }'.

96           task: () => new Listr(mergeConfigs(includeConfig), { exitOnError: true }),
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@types/listr/index.d.ts:33:15
    33         task: (ctx: Ctx, task: ListrTaskWrapper<Ctx>) => void | ListrTaskResult<Ctx>;
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from the return type of this signature.
  src/dev/run_i18n_check.ts:96:17
    96           task: () => new Listr(mergeConfigs(includeConfig), { exitOnError: true }),
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Did you mean to mark this function as 'async'?

src/dev/run_i18n_check.ts:103:13 - error TS2322: Type 'Listr<{ reporter: ErrorReporter; config: I18nConfig; }>' is not assignable to type 'void | ListrTaskResult<{ config: I18nConfig; }>'.
  Type 'Listr<{ reporter: ErrorReporter; config: I18nConfig; }>' is not assignable to type 'Listr<{ config: I18nConfig; }>'.
    Types of property 'setRenderer' are incompatible.
      Type '(value: ListrRendererValue<{ reporter: ErrorReporter; config: I18nConfig; }>) => void' is not assignable to type '(value: ListrRendererValue<{ config: I18nConfig; }>) => void'.
        Types of parameters 'value' and 'value' are incompatible.
          Type 'ListrRendererValue<{ config: I18nConfig; }>' is not assignable to type 'ListrRendererValue<{ reporter: ErrorReporter; config: I18nConfig; }>'.
            Type 'ListrRendererClass<{ config: I18nConfig; }>' is not assignable to type 'ListrRendererValue<{ reporter: ErrorReporter; config: I18nConfig; }>'.
              Type 'ListrRendererClass<{ config: I18nConfig; }>' is not assignable to type 'ListrRendererClass<{ reporter: ErrorReporter; config: I18nConfig; }>'.
                Types of parameters 'tasks' and 'tasks' are incompatible.
                  Type 'readonly ListrTaskObject<{ reporter: ErrorReporter; config: I18nConfig; }>[]' is not assignable to type 'readonly ListrTaskObject<{ config: I18nConfig; }>[]'.
                    Type 'ListrTaskObject<{ reporter: ErrorReporter; config: I18nConfig; }>' is not assignable to type 'ListrTaskObject<{ config: I18nConfig; }>'.
                      Types of property 'task' are incompatible.
                        Type '(ctx: { reporter: ErrorReporter; config: I18nConfig; }, task: ListrTaskWrapper<{ reporter: ErrorReporter; config: I18nConfig; }>) => void | ListrTaskResult<{ reporter: ErrorReporter; config: I18nConfig; }>' is not assignable to type '(ctx: { config: I18nConfig; }, task: ListrTaskWrapper<{ config: I18nConfig; }>) => void | ListrTaskResult<{ config: I18nConfig; }>'.
                          Types of parameters 'ctx' and 'ctx' are incompatible.
                            Type '{ config: I18nConfig; }' is not assignable to type '{ reporter: ErrorReporter; config: I18nConfig; }'.

103             new Listr(extractUntrackedMessages(srcPaths), { exitOnError: true }),
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@types/listr/index.d.ts:33:15
    33         task: (ctx: Ctx, task: ListrTaskWrapper<Ctx>) => void | ListrTaskResult<Ctx>;
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from the return type of this signature.
  src/dev/run_i18n_check.ts:102:17
    102           task: ({ config }) =>
                        ~~~~~~~~~~~~~~~
    103             new Listr(extractUntrackedMessages(srcPaths), { exitOnError: true }),
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Did you mean to mark this function as 'async'?

src/dev/run_i18n_check.ts:109:13 - error TS2322: Type 'Listr<{ messages: Map<string, { message: string; }>; reporter: ErrorReporter; }>' is not assignable to type 'void | ListrTaskResult<{ config: I18nConfig; }>'.
  Type 'Listr<{ messages: Map<string, { message: string; }>; reporter: ErrorReporter; }>' is not assignable to type 'Listr<{ config: I18nConfig; }>'.
    Types of property 'tasks' are incompatible.
      Type 'readonly ListrTaskWrapper<{ messages: Map<string, { message: string; }>; reporter: ErrorReporter; }>[]' is not assignable to type 'readonly ListrTaskWrapper<{ config: I18nConfig; }>[]'.
        Type 'ListrTaskWrapper<{ messages: Map<string, { message: string; }>; reporter: ErrorReporter; }>' is not assignable to type 'ListrTaskWrapper<{ config: I18nConfig; }>'.
          Type '{ messages: Map<string, { message: string; }>; reporter: ErrorReporter; }' is not assignable to type '{ config: I18nConfig; }'.

109             new Listr(extractDefaultMessages(config, srcPaths), { exitOnError: true }),
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@types/listr/index.d.ts:33:15
    33         task: (ctx: Ctx, task: ListrTaskWrapper<Ctx>) => void | ListrTaskResult<Ctx>;
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from the return type of this signature.
  src/dev/run_i18n_check.ts:108:17
    108           task: ({ config }) =>
                        ~~~~~~~~~~~~~~~
    109             new Listr(extractDefaultMessages(config, srcPaths), { exitOnError: true }),
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Did you mean to mark this function as 'async'?

src/dev/run_i18n_check.ts:115:13 - error TS2322: Type 'Listr<{ messages: Map<string, { message: string; }>; }>' is not assignable to type 'void | ListrTaskResult<{ config: I18nConfig; }>'.
  Type 'Listr<{ messages: Map<string, { message: string; }>; }>' is not assignable to type 'Listr<{ config: I18nConfig; }>'.
    Types of property 'tasks' are incompatible.
      Type 'readonly ListrTaskWrapper<{ messages: Map<string, { message: string; }>; }>[]' is not assignable to type 'readonly ListrTaskWrapper<{ config: I18nConfig; }>[]'.
        Type 'ListrTaskWrapper<{ messages: Map<string, { message: string; }>; }>' is not assignable to type 'ListrTaskWrapper<{ config: I18nConfig; }>'.
          Type '{ messages: Map<string, { message: string; }>; }' is not assignable to type '{ config: I18nConfig; }'.

115             new Listr(
                ~~~~~~~~~~
116               checkCompatibility(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
127               { exitOnError: true }
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
128             ),
    ~~~~~~~~~~~~~

  node_modules/@types/listr/index.d.ts:33:15
    33         task: (ctx: Ctx, task: ListrTaskWrapper<Ctx>) => void | ListrTaskResult<Ctx>;
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from the return type of this signature.
  src/dev/run_i18n_check.ts:114:17
    114           task: ({ config }) =>
                        ~~~~~~~~~~~~~~~
    115             new Listr(
        ~~~~~~~~~~~~~~~~~~~~~~
    ... 
    127               { exitOnError: true }
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    128             ),
        ~~~~~~~~~~~~~
    Did you mean to mark this function as 'async'?

src/dev/run_i18n_check.ts:140:24 - error TS2345: Argument of type '{ messages: Map<string, { message: string; }>; reporter: any; }' is not assignable to parameter of type '{ config: I18nConfig; }'.
  Object literal may only specify known properties, and 'messages' does not exist in type '{ config: I18nConfig; }'.

140       await list.run({ messages, reporter });
                           ~~~~~~~~

src/dev/run_i18n_extract.ts:62:18 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(tasks?: readonly ListrTask<{ reporter: ErrorReporter; config?: I18nConfig | undefined; }>[] | undefined, options?: ListrOptions<{ reporter: ErrorReporter; config?: I18nConfig | undefined; }> | undefined): Listr<...>', gave the following error.
    Type 'Listr<{ messages: Map<string, { message: string; }>; reporter: ErrorReporter; }>' is not assignable to type 'void | ListrTaskResult<{ reporter: ErrorReporter; config?: I18nConfig | undefined; }>'.
      Type 'Listr<{ messages: Map<string, { message: string; }>; reporter: ErrorReporter; }>' is not assignable to type 'Listr<{ reporter: ErrorReporter; config?: I18nConfig | undefined; }>'.
        Types of property 'setRenderer' are incompatible.
          Type '(value: ListrRendererValue<{ messages: Map<string, { message: string; }>; reporter: ErrorReporter; }>) => void' is not assignable to type '(value: ListrRendererValue<{ reporter: ErrorReporter; config?: I18nConfig | undefined; }>) => void'.
            Types of parameters 'value' and 'value' are incompatible.
              Type 'ListrRendererValue<{ reporter: ErrorReporter; config?: I18nConfig | undefined; }>' is not assignable to type 'ListrRendererValue<{ messages: Map<string, { message: string; }>; reporter: ErrorReporter; }>'.
                Type 'ListrRendererClass<{ reporter: ErrorReporter; config?: I18nConfig | undefined; }>' is not assignable to type 'ListrRendererValue<{ messages: Map<string, { message: string; }>; reporter: ErrorReporter; }>'.
                  Type 'ListrRendererClass<{ reporter: ErrorReporter; config?: I18nConfig | undefined; }>' is not assignable to type 'ListrRendererClass<{ messages: Map<string, { message: string; }>; reporter: ErrorReporter; }>'.
                    Types of parameters 'tasks' and 'tasks' are incompatible.
                      Type 'readonly ListrTaskObject<{ messages: Map<string, { message: string; }>; reporter: ErrorReporter; }>[]' is not assignable to type 'readonly ListrTaskObject<{ reporter: ErrorReporter; config?: I18nConfig | undefined; }>[]'.
                        Type 'ListrTaskObject<{ messages: Map<string, { message: string; }>; reporter: ErrorReporter; }>' is not assignable to type 'ListrTaskObject<{ reporter: ErrorReporter; config?: I18nConfig | undefined; }>'.
                          Types of property 'task' are incompatible.
                            Type '(ctx: { messages: Map<string, { message: string; }>; reporter: ErrorReporter; }, task: ListrTaskWrapper<{ messages: Map<string, { message: string; }>; reporter: ErrorReporter; }>) => void | ListrTaskResult<...>' is not assignable to type '(ctx: { reporter: ErrorReporter; config?: I18nConfig | undefined; }, task: ListrTaskWrapper<{ reporter: ErrorReporter; config?: I18nConfig | undefined; }>) => void | ListrTaskResult<...>'.
                              Types of parameters 'ctx' and 'ctx' are incompatible.
                                Type '{ reporter: ErrorReporter; config?: I18nConfig | undefined; }' is not assignable to type '{ messages: Map<string, { message: string; }>; reporter: ErrorReporter; }'.
  Overload 2 of 2, '(options?: ListrOptions<any> | undefined): Listr<any>', gave the following error.
    Type '({ title: string; task: () => Listr<{ reporter: ErrorReporter; config?: I18nConfig | undefined; }>; } | { title: string; task: ({ config }: { reporter: ErrorReporter; config?: I18nConfig | undefined; }) => Listr<...>; } | { ...; })[]' has no properties in common with type 'ListrOptions<any>'.

 62     const list = new Listr([
                     ~~~~~~~~~~~
 63       {
    ~~~~~~~
... 
 86       },
    ~~~~~~~~
 87     ]);
    ~~~~~~

  node_modules/@types/listr/index.d.ts:33:15
    33         task: (ctx: Ctx, task: ListrTaskWrapper<Ctx>) => void | ListrTaskResult<Ctx>;
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from the return type of this signature.
  src/dev/run_i18n_extract.ts:69:15
    69         task: ({ config }) =>
                     ~~~~~~~~~~~~~~~
    70           new Listr(extractDefaultMessages(config, srcPaths), { exitOnError: true }),
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Did you mean to mark this function as 'async'?

src/dev/run_i18n_extract.ts:70:44 - error TS2345: Argument of type 'I18nConfig | undefined' is not assignable to parameter of type 'I18nConfig'.
  Type 'undefined' is not assignable to type 'I18nConfig'.

70           new Listr(extractDefaultMessages(config, srcPaths), { exitOnError: true }),
                                              ~~~~~~

src/dev/run_i18n_extract.ts:74:44 - error TS2339: Property 'messages' does not exist on type '{ reporter: ErrorReporter; config?: I18nConfig | undefined; }'.

74         enabled: (ctx) => outputDir && ctx.messages.size,
                                              ~~~~~~~~

src/dev/run_i18n_extract.ts:76:42 - error TS2339: Property 'messages' does not exist on type '{ reporter: ErrorReporter; config?: I18nConfig | undefined; }'.

76           const sortedMessages = [...ctx.messages].sort(([key1], [key2]) =>
                                            ~~~~~~~~

src/dev/run_i18n_extract.ts:92:24 - error TS2345: Argument of type '{ messages: Map<string, { message: string; }>; reporter: any; }' is not assignable to parameter of type '{ reporter: ErrorReporter; config?: I18nConfig | undefined; }'.
  Object literal may only specify known properties, and 'messages' does not exist in type '{ reporter: ErrorReporter; config?: I18nConfig | undefined; }'.

92       await list.run({ messages, reporter });
                          ~~~~~~~~

src/dev/run_i18n_integrate.ts:93:18 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(tasks?: readonly ListrTask<{ reporter: ErrorReporter; config?: I18nConfig | undefined; }>[] | undefined, options?: ListrOptions<{ reporter: ErrorReporter; config?: I18nConfig | undefined; }> | undefined): Listr<...>', gave the following error.
    Type 'Listr<{ messages: Map<string, { message: string; }>; reporter: ErrorReporter; }>' is not assignable to type 'void | ListrTaskResult<{ reporter: ErrorReporter; config?: I18nConfig | undefined; }>'.
  Overload 2 of 2, '(options?: ListrOptions<any> | undefined): Listr<any>', gave the following error.
    Type '({ title: string; task: () => Listr<{ reporter: ErrorReporter; config?: I18nConfig | undefined; }>; } | { title: string; task: ({ config }: { reporter: ErrorReporter; config?: I18nConfig | undefined; }) => Listr<...>; } | { ...; })[]' has no properties in common with type 'ListrOptions<any>'.

 93     const list = new Listr([
                     ~~~~~~~~~~~
 94       {
    ~~~~~~~
... 
118       },
    ~~~~~~~~
119     ]);
    ~~~~~~

  node_modules/@types/listr/index.d.ts:33:15
    33         task: (ctx: Ctx, task: ListrTaskWrapper<Ctx>) => void | ListrTaskResult<Ctx>;
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from the return type of this signature.
  src/dev/run_i18n_integrate.ts:100:15
    100         task: ({ config }) =>
                      ~~~~~~~~~~~~~~~
    101           new Listr(extractDefaultMessages(config, srcPaths), { exitOnError: true }),
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Did you mean to mark this function as 'async'?

src/dev/run_i18n_integrate.ts:101:44 - error TS2345: Argument of type 'I18nConfig | undefined' is not assignable to parameter of type 'I18nConfig'.
  Type 'undefined' is not assignable to type 'I18nConfig'.

101           new Listr(extractDefaultMessages(config, srcPaths), { exitOnError: true }),
                                               ~~~~~~

src/dev/run_i18n_integrate.ts:105:24 - error TS2339: Property 'messages' does not exist on type '{ reporter: ErrorReporter; config?: I18nConfig | undefined; }'.

105         task: async ({ messages, config }) => {
                           ~~~~~~~~

src/dev/run_i18n_integrate.ts:114:13 - error TS2322: Type 'I18nConfig | undefined' is not assignable to type 'I18nConfig'.
  Type 'undefined' is not assignable to type 'I18nConfig'.

114             config,
                ~~~~~~

  src/dev/i18n/integrate_locale_files.ts:59:3
    59   config: I18nConfig;
         ~~~~~~
    The expected type comes from property 'config' which is declared here on type 'IntegrateOptions'

src/dev/run_i18n_integrate.ts:124:24 - error TS2345: Argument of type '{ messages: Map<string, { message: string; }>; reporter: any; }' is not assignable to parameter of type '{ reporter: ErrorReporter; config?: I18nConfig | undefined; }'.
  Object literal may only specify known properties, and 'messages' does not exist in type '{ reporter: ErrorReporter; config?: I18nConfig | undefined; }'.

124       await list.run({ messages, reporter });


```

### PR DESCRIPTION
**Pull request by Nicksqain**
### Description

- Corrects error types of error handlers.
- Corrects type errors for i18n and its configs.
- Setting the type of the context for each of the helper functions and the list.

### Issues Resolved
 #3027
 
### Check List
- [x] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

File: src/dev/run_i18n_check.ts [hunk 1]
```diff
@@ -105,16 +110,17 @@ run(
...
         },
         {
           title: 'Compatibility Checks',
           skip: skipOnNoTranslations,
-          task: ({ config }) =>
+          task: ({ config }) => {
             new Listr(
               checkCompatibility(
-                config,
+                config!,
```
Comment (ashwin-pc) [inline src/dev/run_i18n_check.ts:123]: Same here, you dont need this change.

File: src/dev/run_i18n_check.ts [hunk 2]
```diff
@@ -105,16 +110,17 @@ run(
...
-            new Listr(extractDefaultMessages(config, srcPaths), { exitOnError: true }),
+          task: ({ config }) => {
+            return new Listr(extractDefaultMessages(config!, srcPaths), { exitOnError: true });
+          },
         },
         {
           title: 'Compatibility Checks',
           skip: skipOnNoTranslations,
-          task: ({ config }) =>
+          task: ({ config }) => {
```
Comment (ashwin-pc) [inline src/dev/run_i18n_check.ts:120]: you added the brackets but forgot to return the `Listr` instance

File: src/dev/run_i18n_integrate.ts [hunk 3]
```diff
@@ -90,30 +91,32 @@ run(
...
+    const list = new Listr<ListrContext>([
       {
         title: 'Merging .i18nrc.json files',
         task: () => new Listr(mergeConfigs(includeConfig), { exitOnError: true }),
       },
       {
         title: 'Extracting Default Messages',
         task: ({ config }) =>
-          new Listr(extractDefaultMessages(config, srcPaths), { exitOnError: true }),
+          new Listr(extractDefaultMessages(config!, srcPaths), { exitOnError: true }),
```
Comment (ashwin-pc) [inline src/dev/run_i18n_integrate.ts:102]: same here, you dont need this change

File: src/dev/run_i18n_integrate.ts [hunk 4]
```diff
@@ -90,30 +91,32 @@ run(
...
-            targetFileName: target,
-            dryRun,
-            ignoreIncompatible,
-            ignoreUnused,
-            ignoreMissing,
-            ignoreMalformed,
-            config,
-            log,
-          });
+          if (config) {
```
Comment (ashwin-pc) [inline src/dev/run_i18n_integrate.ts:107]: I like you pattern of throwing an error if config is missing instead of this

**Review by ashwin-pc — COMMENTED** [review]
I like this PR, great job! just a few small comments but mostly there 😄

File: src/dev/run_i18n_check.ts (hunk 1 above)
Comment (Nicksqain) [reply src/dev/run_i18n_check.ts:123]: Yes, inside the function I did a check for the presence of a config. but there was still an error, although I did the same thing in another function, so I set it to ignore, since I am sure that there will be an error without the config. I will try to fix it somehow, if I succeed

File: src/dev/i18n/utils/verify_icu_message.ts [hunk 5]
```diff
@@ -70,16 +70,20 @@ export function verifyICUMessage(message: string) {
...
+              line: error.location.start.line,
+              column: error.location.start.column - 1,
+            },
+            message: error.message,
+          });
+          throw errorWithContext;
+        }
+      }
     }
   }
```
[the remark this answers is not in the document]
Comment (Nicksqain) [reply src/dev/i18n/utils/verify_icu_message.ts:88]: I wasn't sure if the error would be instance of parser.SyntaxError, so I left it so to get your opinion. I'll change it if it's right

File: src/dev/run_i18n_check.ts (hunk 1 above)
Comment (Nicksqain) [reply src/dev/run_i18n_check.ts:123]: Wouldn't it be more appropriate to check for config when called? i.e. if(config){}
otherwise the function itself will have to describe config: i18nConfig | undefined.

File: src/dev/run_i18n_check.ts [hunk 6]
```diff
@@ -105,16 +110,17 @@ run(
         {
           title: 'Validating Default Messages',
           skip: skipOnNoTranslations,
-          task: ({ config }) =>
-            new Listr(extractDefaultMessages(config, srcPaths), { exitOnError: true }),
+          task: ({ config }) => {
+            return new Listr(extractDefaultMessages(config!, srcPaths), { exitOnError: true });
```
[the remark this answers is not in the document]
Comment (Nicksqain) [reply src/dev/run_i18n_check.ts:114]: Can skipOnNoTranslations do a throw error if there is no config? So as not to create more checks. Although these functions will be used anyway and there is no other way to check if the config is in one place

File: src/dev/run_i18n_check.ts (hunk 1 above)
Comment (ashwin-pc) [reply src/dev/run_i18n_check.ts:123]: Yeah, i leave that to you. The only thing i'm really looking for is a consistent type for the context so that i makes readability easier. So i like the optional type for `config` and if you need to add a check for config in the helper functions to get rid of the error, thats okay by me :)

**Comment by joshuarrrr** [comment]
@Nicksqain When you add the next commits based on the review feedback, please also add an entry to the `CHANGELOG.md` file (under the "Refactoring" section).

File: src/dev/run_i18n_extract.ts [hunk 7]
```diff
@@ -35,7 +35,7 @@ import { resolve } from 'path';
 import { createFailError, run } from '@osd/dev-utils';
 import { ErrorReporter, serializeToJson, serializeToJson5, writeFileAsync } from './i18n';
 import { extractDefaultMessages, mergeConfigs } from './i18n/tasks';
-
+import { ListrContext } from './run_i18n_check';
```
Comment (ashwin-pc) [inline src/dev/run_i18n_extract.ts:38]: Nit: This can come from a common source instead of another file.

File: src/dev/run_i18n_extract.ts [hunk 8]
```diff
@@ -59,19 +59,19 @@ run(
...
+    const list = new Listr<ListrContext>([
       {
         title: 'Merging .i18nrc.json files',
         task: () => new Listr(mergeConfigs(includeConfig), { exitOnError: true }),
       },
       {
         title: 'Extracting Default Messages',
         task: ({ config }) =>
-          new Listr(extractDefaultMessages(config, srcPaths), { exitOnError: true }),
+          new Listr(extractDefaultMessages(config!, srcPaths), { exitOnError: true }),
```
Comment (ashwin-pc) [inline src/dev/run_i18n_extract.ts:70]:
```suggestion
          new Listr(extractDefaultMessages(config, srcPaths), { exitOnError: true }),
```

update `extractDefaultMessages` to accept an optional config just like `checkCompatibility`. This should never happen based on the order that they are called in, but should the order ever be swapped, the error will point us to the problem

File: src/dev/run_i18n_integrate.ts (hunk 4 above)
Comment (ashwin-pc) [reply src/dev/run_i18n_integrate.ts:107]: Looks like you missed this change. The reason i like throwing an error is because it makes it clear why the task failed. The config should never be empty, but if it is, based on this change this task will complete silently, but the other tasks like `checkCompatibility` will throw an error. And since we expect config to be defined in this task, I want to know if it did not run.

**Review by ashwin-pc — COMMENTED** [review]
Thanks for making the changes @Nicksqain. Just a few last comments and this PR should be good to merge :)

File: src/dev/run_i18n_extract.ts (hunk 7 above)
Comment (Nicksqain) [reply src/dev/run_i18n_extract.ts:38]: ./i18n/tasks or ./i18n. Right?

**Review by ashwin-pc — APPROVED** [review]
👍 Awesome job on your pull request! Thanks for the contribution! 🎉

**Comment by ashwin-pc** [comment]
@Nicksqain I did notice however that typescript still complains about the `verify_icu_message.ts` file. Didnt want to block the PR because we can fix it later too, but just wanted to call that out.

**Comment by Nicksqain** [comment]
@ashwin-pc Where exactly is the typescript error?

**Comment by Nicksqain** [comment]
> Screenshot 2023-03-29 at 10 33 19 AM

I created an issue for this problem #3606
There are two solutions, but the second one is not bad either.

- [ ] 1. We need to update dependencies for parser to solve this problem.
- [ ] 2. I can solve it here too by applying template literals by concatenating all parser.SyntaxError arguments. What do you think?

**Comment by joshuarrrr** [comment]
@Nicksqain Given https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3606, I'd strongly prefer to update the deprecated dependency, so no need to account for it in this PR.

**Review by joshuarrrr — APPROVED** [review]
Thanks so much!
