### PR TITLE
[FIX] Dashboard list integrated delete

### LINKED ISSUE #3795: [BUG] Delete Dashboard not working after Integrated Plugin feature
**Describe the bug**

Can't delete Dashboards w/ new Integrated Plugin feature.

**To Reproduce**
1. Go to 'Dashboards / Dashboards' (The list view)
2. Click on 'Checkbox any "Dashboard" type item'
3. Click on "Delete [n] Dashbaords" (red box next to search)
4. See error toast
5. Also see failed POST in Networking tool, and Console logged error

**Expected behavior**
Successful delete and item removed from list immediately.

**OpenSearch Version**
2.x (main)

**Dashboards Version**
2.x (main)

**Plugins**

Observability

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

### PR DESCRIPTION
**Pull request by pjfitzgibbons**
### Description

Fix delete on Dashboard items with Integrated Providers feature

### Issues Resolved

resolves #3795 

### Check List

- [x] All tests pass
  - [x] `yarn test:jest`
  - [x] `yarn test:jest_integration`
  - [x] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by joshuarrrr** [comment]
@pjfitzgibbons One of the commits is missing the sign-off for DCO: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3796/checks?check_run_id=12607666399

File: src/plugins/dashboard/public/plugin.tsx [hunk 1]
```diff
@@ -344,7 +344,7 @@ export class DashboardPlugin
     registerDashboardProvider({
       savedObjectsType: 'dashboard',
       savedObjectsName: 'Dashboard',
-      appId: 'dashboards',
+      appId: 'dashboard',
```
Comment (joshuarrrr) [inline src/plugins/dashboard/public/plugin.tsx:347]: This does seem better - was it necessary as part of this fix?

File: src/plugins/dashboard/public/application/legacy_app.js [hunk 2]
```diff
@@ -171,7 +170,12 @@ export function initDashboardApp(app, deps) {
             history.push(deps.addBasePath(viewUrl));
           };
           $scope.delete = (dashboards) => {
-            return service.delete(dashboards.map((d) => d.id));
+            const ids = dashboards.map((d) => ({ id: d.id, appId: d.appId }));
+            return Promise.all(
+              ids.map(({ id, appId }) => {
+                return deps.savedObjectsClient.delete(appId, id);
+              })
+            );
```
Comment (joshuarrrr) [inline src/plugins/dashboard/public/application/legacy_app.js:178]: @pjfitzgibbons Can you explain this fix a bit more? Is there a reason why you switched from using the `savedDashbaoards` service to using the `savedObjectsClient` directly? It seems like the old way would potentially be preferable if it actually is a bulk action under the hood rather than multiple calls with client for each object (although I don't remember enough about the implementation under the hood to know if it's actually a bulk operation or whether it does a similar loop).

**Review by joshuarrrr — COMMENTED** [review]
@pjfitzgibbons For a bug fix like this, I'd expect a regression test case. Is the deletion case covered by any of the functional or unit tests? If you have a screencast that shows bulk and individual delete operations working, that's always helpful too.

Otherwise just some minor questions about the implementation choices and nature of the bug.

**Comment by joshuarrrr** [comment]
@pjfitzgibbons Just checking in on this - code freeze is Monday, so we'd like to be able to merge before then.

File: src/plugins/dashboard/public/plugin.tsx (hunk 1 above)
Comment (abbyhu2000) [reply src/plugins/dashboard/public/plugin.tsx:347]: yea it seems to me that this is not part of the fix. Is there an underlying reason to change the `appId`?

File: src/plugins/dashboard/public/application/legacy_app.js (hunk 2 above)
Comment (pjfitzgibbons) [reply src/plugins/dashboard/public/application/legacy_app.js:178]: Unless You Know Better :) .... there is no API on SavedObject that I can bulk-delete a collection of {id:, type:}, since the dashboard-list _could_ contain multiple plugin's items, ... different "type"s... so the SavedObjectSevice is no longer an adequate API for this.
The alternative, and workaround for 2.7, is to iterate the selected list and delete.   

This *should* be a rarely-used API, and the most any user could select is all 50 (100?) listed on a single page, so even that is not horrible abuse of the API (might take a minute to complete).

Thoughts? @joshuarrrr @abbyhu2000

File: src/plugins/dashboard/public/plugin.tsx (hunk 1 above)
Comment (pjfitzgibbons) [reply src/plugins/dashboard/public/plugin.tsx:347]: This was necessary in order to accomodate the code change at `$scope.delete`, which now depends upon the item's "type" to delete... dashboard items are type "dashboard", so this correction.

See. Legacy_app.js : 174

**Comment by pjfitzgibbons** [comment]
> @pjfitzgibbons For a bug fix like this, I'd expect a regression test case. Is the deletion case covered by any of the functional or unit tests? If you have a screencast that shows bulk and individual delete operations working, that's always helpful too.
> 
> Otherwise just some minor questions about the implementation choices and nature of the bug.

Existing test cases should cover.  There are delete cases, no-error means refactor has not changed behaviour.

Do we have test cases that specifically cover "optional" plugin-available APIs ?

**Comment by pjfitzgibbons** [comment]
> @pjfitzgibbons One of the commits is missing the sign-off for DCO: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3796/checks?check_run_id=12607666399

Fixed.  (squashed the branch)

**Comment by abbyhu2000** [comment]
Ran the code and functionality looks good with deleting the dashboards. Have not tried deleting with the new dashboard list functionality.

File: src/plugins/dashboard/public/application/legacy_app.js (hunk 2 above)
Comment (joshuarrrr) [inline src/plugins/dashboard/public/application/legacy_app.js:178]: For consistency with the visualizations list, we should at least fire a toast if there's a deletion error:
```suggestion
            return Promise.all(
              ids.map(({ id, appId }) => {
                return deps.savedObjectsClient.delete(appId, id);
              })
            ).catch((error) => {
              toastNotifications.addError(error, {
                title: i18n.translate('dashboard.dashboardListingDeleteErrorTitle', {
                  defaultMessage: 'Error deleting dashboard',
                }),
              });
            });
```

Comment (joshuarrrr) [reply src/plugins/dashboard/public/application/legacy_app.js:178]: Yeah - confirmed this is what we do in `visualize`: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/685c9115f4779e2743acbd3d2ff17e6c3d4ee6b3/src/plugins/visualize/public/application/components/visualize_listing.tsx#L135-L148

**Review by joshuarrrr — COMMENTED** [review]
@pjfitzgibbons This looks good - if you can add the suggested error toast, we should be ready to go.

**Comment by joshuarrrr** [comment]
> Existing test cases should cover. There are delete cases, no-error means refactor has not changed behaviour.
> 
> Do we have test cases that specifically cover "optional" plugin-available APIs ?

So this bug was only for deleting objects that used the new interface (deleting legacy dashboards worked fine)? If that's the case, then yeah, we'd want to update our test cases to include mock non-dashboard objects that use the new interface that validates those functionalities.

**Comment by joshuarrrr** [comment]
(current test failures can be ignored)

File: CHANGELOG.md [hunk 3]
```diff
@@ -116,6 +116,7 @@ Inspired from [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)
 - Clean up and rebuild `@osd/pm` ([#3570](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3570))
 - [Vega] Add Filter custom label for opensearchDashboardsAddFilter ([#3640](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3640))
 - [Timeline] Fix y-axis label color in dark mode ([#3698](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3698))
+- [Dashboard] Fix Dashboard-Delete from Dashboards / Dashboards (broken by #3090) ([#3796](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3796))
```
Comment (AMoo-Miki) [inline CHANGELOG.md:119]: Reading this, with no context, I am not sure what the change is or is trying to fix. Can we reword this please?

**Comment by abbyhu2000** [comment]
Also need to be rebased to fix the link and cypress tests and the merge conflicts. @pjfitzgibbons

**Comment by joshuarrrr** [comment]
@abbyhu2000 See https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3796#issuecomment-1509216678 - those failures are unrelated. But given the changelog conflict, I'll resolve and restart the automation.

File: CHANGELOG.md (hunk 3 above)
Comment (joshuarrrr) [reply CHANGELOG.md]: There's no need for a changelog entry here, as this bug was only introduced in a 2.7 feature.

**Comment by kavilla** [comment]
@pjfitzgibbons, attempting to recreate the error on main with and without an extra plugin registering but not able to recreate it.

Are you still seeing this issue? What was the error from the toast?

**Comment by joshuarrrr** [comment]
> @pjfitzgibbons, attempting to recreate the error on main with and without an extra plugin registering but not able to recreate it.
> 
> Are you still seeing this issue? What was the error from the toast?

I believe deleting existing dashboard items worked fine - so you'd need to have a non-dashboard item registered to be able to delete and see the error, which is what I suggested in terms of test expansion.

**Comment by joshuarrrr** [comment]
All checks passed.

**Comment by pjfitzgibbons** [comment]
I'll look at testing tomorrow.

**Review by joshuarrrr — APPROVED** [review]

File: src/plugins/dashboard/public/application/legacy_app.js [hunk 4]
```diff
@@ -171,7 +170,18 @@ export function initDashboardApp(app, deps) {
...
+              ids.map(({ id, appId }) => {
+                return deps.savedObjectsClient.delete(appId, id);
+              })
+            ).catch((error) => {
+              deps.toastNotifications.addError(error, {
+                title: i18n.translate('dashboard.dashboardListingDeleteErrorTitle', {
+                  defaultMessage: 'Error deleting dashboard',
+                }),
+              });
+            });
```
Comment (AMoo-Miki) [inline src/plugins/dashboard/public/application/legacy_app.js:184]: If I understand this correctly, we fire off a bunch of `delete` requests in parallel and if one fails we show an error that there was a problem deleting the "dashboard" but in reality, we have deleted some stuff. This doesn't sound like good UX.

File: src/plugins/dashboard/public/application/legacy_app.js [hunk 5]
```diff
@@ -171,7 +170,18 @@ export function initDashboardApp(app, deps) {
             history.push(deps.addBasePath(viewUrl));
           };
           $scope.delete = (dashboards) => {
-            return service.delete(dashboards.map((d) => d.id));
+            const ids = dashboards.map((d) => ({ id: d.id, appId: d.appId }));
```
Comment (AMoo-Miki) [inline src/plugins/dashboard/public/application/legacy_app.js:173]: Any reason why this `map` is not combined with the `map` inside the `all`?

File: src/plugins/dashboard/public/application/legacy_app.js (hunk 4 above)
Comment (joshuarrrr) [reply src/plugins/dashboard/public/application/legacy_app.js:184]: I think we want to go with consistent UX (so that the same component on `dashboard` and `visualize` behaves the same) first, and then we can improve the existing UX in a follow-up.

**Review by ashwin-pc — APPROVED** [review]

File: src/plugins/dashboard/public/application/legacy_app.js (hunk 4 above)
Comment (joshuarrrr) [reply src/plugins/dashboard/public/application/legacy_app.js:184]: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3877
