### PR TITLE
[Chore] Visualize link fix

### LINKED ISSUE #2197: [BUG] Cannot open visualisations in new windows or tabs
**Describe the bug**
If I go to /app/dashboards then I can middle click or right click on a dashboard in the list and open in a new window/tab
If I go to /app/visualize then I **cannot** middle click or right click on a visualization in the list to open in a new window/tab

**To Reproduce**
1. Go to /app/visualize
2. Try to open a visualization in a new tab or window (either by middle clicking, or right clicking) and note that it is not possible

**Expected behavior**
I expected to be able to open visualizations in new tabs and windows, much like is possible for /app/dashboards.

**Screenshots**
Visualize:
image
Dashboards:
image

**OpenSearch Version**
1.3.4

**Dashboards Version**
1.3.4

**Plugins**
security-dashboards-plugin

**Host/Environment (please complete the following information):**
 - Docker

### PR DESCRIPTION
**Pull request by BSFishy**
### Description
Change the links in the visualize plugin to use `href` rather than `onClick`. This is beneficial, as it allows links to be opened in new tabs, and helps with accessibility, as the elements are `a` instead of `button` now.
 
### Issues Resolved
#2197 
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
    - [x] `yarn test:jest`
    - [x] `yarn test:jest_integration`
    - [x] `yarn test:ftr`
- [ ] New functionality has been documented.
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by ashwin-pc — CHANGES_REQUESTED** [review]
This fix does not work with aliased visualizations. e.g. Vis Builder aka Wizard.

I didn't look too closely into why but the steps to repro this are:
1. Enable Wizard: Set the last flag in `opensearch_dashboards.yml` config to true `wizard.enabled:true`
1. Create a new visualization using the wizard type and save it
2. Go to the visualization table and try to edit it

You should see 
Screen Shot 2022-09-22 at 1 37 30 AM

**Comment by BSFishy** [comment]
Also, something that just came to me that I think might be up for discussion is link prefetching. It's out of the scope of this issue and PR, but I think that it might be useful. I don't think the regular load speed is much of an issue, but if the link is opened in a new tab, the page can take a little bit of time to load which I think prefetching would help with. Should I open a new issue to discuss this further?

cc @ashwin-pc @kavilla

**Comment by bandinib-amzn** [comment]
> This fix does not work with aliased visualizations. e.g. Vis Builder aka Wizard.
> 
> I didn't look too closely into why but the steps to repro this are:
> 
> 1. Enable Wizard: Set the last flag in `opensearch_dashboards.yml` config to true `wizard.enabled:true`
> 2. Create a new visualization using the wizard type and save it
> 3. Go to the visualization table and try to edit it
> 
> You should see Screen Shot 2022-09-22 at 1 37 30 AM

Hi @ashwin-pc 
I followed your steps to repro the issue but couldn't reproduce it. I'm not getting ```Page not found``` error. I tried both Edit action and Open Link in new tab/new window.

**Comment by BSFishy** [comment]
> > This fix does not work with aliased visualizations. e.g. Vis Builder aka Wizard.
> > I didn't look too closely into why but the steps to repro this are:
> > 
> > 1. Enable Wizard: Set the last flag in `opensearch_dashboards.yml` config to true `wizard.enabled:true`
> > 2. Create a new visualization using the wizard type and save it
> > 3. Go to the visualization table and try to edit it
> > 
> > You should see Screen Shot 2022-09-22 at 1 37 30 AM
> 
> Hi @ashwin-pc I followed your steps to repro the issue but couldn't reproduce it. I'm not getting `Page not found` error. I tried both Edit action and Open Link in new tab/new window.

Hey @bandinib-amzn 
I actually fixed that bug [in this commit](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2395/commits/7ec7c5c3a91d3cbf6d2e5c7816afa0949b5eadbd). You would probably find it again if you pulled from a previous commit, but it should be fixed now.

**Review by ashwin-pc — APPROVED** [review]
Ship it 🚢

File: src/plugins/visualize/public/application/utils/get_table_columns.tsx [hunk 1]
```diff
@@ -108,13 +108,7 @@ export const getTableColumns = (
...
       !error ? (
         <EuiLink
-          onClick={() => {
-            if (editApp) {
-              application.navigateToApp(editApp, { path: editUrl });
-            } else if (editUrl) {
-              history.push(editUrl);
-            }
-          }}
+          href={editApp ? application.getUrlForApp(editApp, { path: editUrl }) : `#${editUrl}`}
```
Comment (joshuarrrr) [inline src/plugins/visualize/public/application/utils/get_table_columns.tsx:111]: @BSFishy I really like the direction you've gone with this, but unfortunately it's not sufficient to hardcode the `#` prefix to the `editUrl`. The reason that works for the `wizard` plugin is that we define `#/` as the `aliasPath` here: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/wizard/public/plugin.ts#L117

My suspicion is that we may need to adjust the way `editUrl` is fetched for aliased visualizations upstream of this component so that it correctly accounts for the `aliasPath`.

**Review by joshuarrrr — CHANGES_REQUESTED** [review]

File: src/plugins/visualize/public/application/utils/get_table_columns.tsx (hunk 1 above)
Comment (BSFishy) [reply src/plugins/visualize/public/application/utils/get_table_columns.tsx:111]: I just did a bit of digging, and I think this should work fine. The reason that it works with the `wizard` plugin is because it defines its own application, causing it to call `getUrlForApp`. Otherwise, it will follow the same functionality that was done by `navigateToUrl`. In that function, a call was made to `history.push`, which is implemented in the `history` package. In that package, they simply prepend a `#` to the beginning of the path:

https://github.com/remix-run/history/blob/3e9dab413f4eda8d6bce565388c5ddb7aeff9f7e/packages/history/index.ts#L693

I can still have it get the url upstream of this component, though, like the `DashboardListing` component does, however in that component, the `getViewUrl` function is a property, which I think would be a breaking change.

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/48fe60b40661c0bb19ed73d3426f5d5ec418887c/src/plugins/dashboard/public/application/listing/dashboard_listing.js#L173-L177

Comment (joshuarrrr) [reply src/plugins/visualize/public/application/utils/get_table_columns.tsx:111]: Ah, thanks for digging into the `history` implementation, that makes sense.

**Review by joshuarrrr — APPROVED** [review]

**Comment by seraphjiang** [comment]
Nice, great job. @BSFishy  and Thanks @ashwin-pc @bandinib-amzn @joshuarrrr for the review.
