### PR TITLE
[Vis Builder] Bug fixes for datasource picker and auto time interval

### LINKED ISSUE #2531: [VisBuilder] [BUG] Date histogram auto bounds says per 0 millisecond
**Describe the bug**

When creatig a date histogram, the auto bounds says "says per 0 millisecond"

**To Reproduce**
1. Create a Wizard visualization
2. Add time field to X axis and edit its agg type to date histogram
3. Exit editing mode
4. See field name as described

**Expected behavior**
Display correct time-range

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

### PR DESCRIPTION
**Pull request by ashwin-pc**
### Description

- Fixes Date histogram auto bounds says per 0 millisecond 
- Fixes Histogram updating bounds when date range updates
- Fixes Switching index pattern while editing agg breaks experience
 
### Issues Resolved
#2531 #2310
 
### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
  - [x] `yarn test:jest_integration`
  - [x] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

File: src/plugins/vis_builder/public/application/components/option.tsx [hunk 1]
```diff
@@ -20,6 +20,7 @@ export const Option: FC<Props> = ({ title, children, initialIsOpen = false }) =>
         buttonContent={title}
         className="vbOption"
         initialIsOpen={initialIsOpen}
+        data-test-subj={`vbOption-${title.replace(/\s+/g, '-')}`}
```
Comment (joshuarrrr) [inline src/plugins/vis_builder/public/application/components/option.tsx:23]: super minor nit, but don't we already have a standard test utility for formatting test subjects like this?

**Review by joshuarrrr — APPROVED** [review]

File: src/plugins/vis_builder/public/application/components/option.tsx (hunk 1 above)
Comment (ashwin-pc) [reply src/plugins/vis_builder/public/application/components/option.tsx:23]: Do you know where that is? I couldn't find it in my scan of the repo.

File: src/plugins/vis_builder/public/visualizations/vislib/common/create_vis.ts [hunk 2]
```diff
@@ -17,5 +19,14 @@ export const createVis = async (
   vis.data.searchSource = await getSearchService().searchSource.create();
   vis.data.searchSource.setField('index', indexPattern);
 
+  const responseAggs = vis.data.aggs.getResponseAggs().filter((agg) => agg.enabled);
+  responseAggs.forEach((agg) => {
+    if (isDateHistogramBucketAggConfig(agg)) {
```
[the remark this answers is not in the document]
Comment (ashwin-pc) [reply src/plugins/vis_builder/public/visualizations/vislib/common/create_vis.ts:24]: Good catch. I know the date_histogram bucket agg wont construct the label correctly without this value, but i dont see any reason why it would be a problem for other aggs too. Also this makes me want to spend a lil more time on this change to understand how the agg timeranges work. will update it in a revision

File: src/plugins/vis_builder/public/application/components/option.tsx (hunk 1 above)
Comment (ashwin-pc) [reply src/plugins/vis_builder/public/application/components/option.tsx:23]: FYI: this is how its done on dashboards: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/dashboard/public/application/listing/dashboard_listing.js#L176

Comment (joshuarrrr) [reply src/plugins/vis_builder/public/application/components/option.tsx:23]: Yeah, I guess not 😞

**Review by joshuarrrr — APPROVED** [review]
I'll admit that I didn't fully follow all the implications of these changes, but this looks much cleaner to me now.

**Comment by ashwin-pc** [comment]
> I'll admit that I didn't fully follow all the implications of these changes, but this looks much cleaner to me now.

Thanks for calling that out. Ideally I shouldn't be clubbing more than a single change in a PR but had to since these were all small changes that would have increased churn a lot of they were separate. That being said let me add comments to each change for future visibility.

**Review by joshuarrrr — APPROVED** [review]

**Review by abbyhu2000 — APPROVED** [review]
Thanks for the comments!
