### PR TITLE
[MD] Fix breadcrumb on listing page and update credential saved object mapping

### LINKED ISSUE #2060: [MD] Fix breadcrumb
Screen Shot 2022-08-03 at 10 49 52 AM

### PR DESCRIPTION
**Pull request by noCharger**
Signed-off-by: Louis Chu <clingzhi@amazon.com>

### Description
Fix breadcrumb on listing page

Screen Shot 2022-08-03 at 4 24 55 PM

Screen Shot 2022-08-03 at 4 28 47 PM

### Issues Resolved
#2060 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
    - [ ] `yarn test:jest`
    - [ ] `yarn test:jest_integration`
    - [ ] `yarn test:ftr`
- [ ] New functionality has been documented.
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

File: src/plugins/data_source/server/saved_objects/credential_saved_objects_type.ts [hunk 1]
```diff
@@ -32,6 +33,7 @@ export const credential: SavedObjectsType = {
       credentialType: { type: 'keyword', index: false },
       credentialMaterials: { type: 'object' },
       description: { type: 'text', index: false },
+      version: { type: 'integer', index: false },
```
Comment (zengyan-amazon) [inline src/plugins/data_source/server/saved_objects/credential_saved_objects_type.ts:36]: do we really need to define these field mappings? shall we just define `type` and `type` like index-pattern does?

**Comment by seraphjiang** [comment]
Add credential is more accurate. 
We don't create credential, credential was created in other system and add here

File: src/plugins/data_source/server/saved_objects/credential_saved_objects_type.ts (hunk 1 above)
Comment (noCharger) [reply src/plugins/data_source/server/saved_objects/credential_saved_objects_type.ts:36]: I'm wondering if we should use explicit mapping rather than dynamic mapping. Because index-pattern only defines 'title' and 'type,' we can easily send adhoc requests via saved object API.

```
curl --include -XPOST http://localhost:5603/qba/api/saved_objects/index-pattern \
    -H "Content-Type: application/json" \
    -H "osd-xsrf: true" \
    -d'{"attributes": {"title": "aaa", "type": "bbb", "adhoc": "abcd"}}'
HTTP/1.1 200 OK

{"type":"index-pattern","id":"a55a5480-13f1-11ed-ac4d-79ddf63b23ce","attributes":{"title":"aaa","type":"bbb","adhoc":"abcd"},"references":[],"migrationVersion":{"index-pattern":"7.6.0"},"updated_at":"2022-08-04T12:33:30.056Z","version":"WzQzLDFd","namespaces":["default"]}%                                                                                                       

curl --include -XPOST http://localhost:5603/qba/api/saved_objects/index-pattern \
    -H "Content-Type: application/json" \
    -H "osd-xsrf: true" \
    -d'{"attributes": {"title": "aaa", "type": "bbb", "adhoc2": "abcd"}}'
HTTP/1.1 200 OK

{"type":"index-pattern","id":"bf1146e0-13f1-11ed-ac4d-79ddf63b23ce","attributes":{"title":"aaa","type":"bbb","adhoc2":"abcd"},"references":[],"migrationVersion":{"index-pattern":"7.6.0"},"updated_at":"2022-08-04T12:34:13.198Z","version":"WzQ0LDFd","namespaces":["default"]}%
```

**Comment by noCharger** [comment]
> Add credential is more accurate. We don't create credential, credential was created in other system and add here

Shall we use `Create Stored Credential` suggested by @KrooshalUX ?

**Comment by seraphjiang** [comment]
> > Add credential is more accurate. We don't create credential, credential was created in other system and add here
> 
> 
> 
> Shall we use `Create Stored Credential` suggested by @KrooshalUX ?

What does that mean?

File: src/plugins/data_source/server/saved_objects/credential_saved_objects_type.ts (hunk 1 above)
Comment (zengyan-amazon) [reply src/plugins/data_source/server/saved_objects/credential_saved_objects_type.ts:36]: you will still have dynamic mapping anyways, isn't it? on line 30 you have `dynamic: false,` which means you still accept arbitrary fields. I don't see big benefit to limit the fields, while it impact the flexibility

**Comment by KrooshalUX** [comment]
While it is correct that we are not "creating credential" , we are creating a record of a stored credential to associate with a data source. Therefore,  the original recommendation from the wireframes "Create Stored Credential" still feels correct, beyond just the breadcrumb (in the header and also changing the buttons to Create vs Save). 

However,  I am working on the correct guidance for this language based on existing patterns within our UI and pulling from other CRUD platforms. I will have a final recommendation during our Friday review and will upload screenshots here as well.

**Comment by noCharger** [comment]
> While it is correct that we are not "creating credential" , we are creating a record of a stored credential to associate with a data source. Therefore, the original recommendation from the wireframes "Create Stored Credential" still feels correct, beyond just the breadcrumb (in the header and also changing the buttons to Create vs Save).
> 
> However, I am working on the correct guidance for this language based on existing patterns within our UI and pulling from other CRUD platforms. I will have a final recommendation during our Friday review and will upload screenshots here as well.

Changed to "Create Stored Credential" for now. Since this issue only for breadcrumb, let's track all others on seperate issue : https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2024

File: src/plugins/data_source/server/saved_objects/credential_saved_objects_type.ts (hunk 1 above)
Comment (noCharger) [reply src/plugins/data_source/server/saved_objects/credential_saved_objects_type.ts:36]: As discussed offline, will keep title and authType

**Review by mpabba3003 — APPROVED** [review]

**Comment by kristenTian** [comment]
I don't think we should add ux label on dev tasks. It can mess up the tracking queue. Since you already created standalone task, let's remove the label from here.

**Review by kristenTian — APPROVED** [review]

**Comment by noCharger** [comment]
> I don't think we should add ux label on dev tasks. It can mess up the tracking queue. Since you already created standalone task, let's remove the label from here.

It's on purpose to help @KrooshalUX track the issues.

**Review by zengyan-amazon — APPROVED** [review]
