### PR TITLE
[Discover] Allow the last column of a table wider than the window to show up properly

### LINKED ISSUE #7056: [BUG] After add more columns, the last column can't show proper context in Legacy Table
**Describe the bug**
Screenshot 2024-06-18 at 3 49 04 PM

**To Reproduce**
1. Go to 'Discover'
2. Click on fields to add
3. Scroll right to the last column

**Expected behavior**
Proper display

**OpenSearch Version**
2.14

**Dashboards Version**
2.14

**Plugins**
NA

### PR DESCRIPTION
**Pull request by AMoo-Miki**
### Description

The last column on a table wider than the screen was crushed.

Screenshot 2024-06-18 at 17-40-34 Discover - OpenSearch Dashboards

### Issues Resolved

Fixes #7056

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [X] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by ananzh — DISMISSED** [review]

**Review by ruanyl — APPROVED** [review]

File: src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx [hunk 1]
```diff
@@ -195,11 +195,9 @@ const DefaultDiscoverTableUI = ({
            * First cell is skipped because it has a dimention set already, and the last cell is skipped to allow it to
```
Comment (ruanyl) [inline src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx:195]: > and the last cell is skipped to allow it to grow as much as the table needs.

Shall we adjust this comment?

**Review by kavilla — APPROVED** [review]

**Review by zhyuanqi — APPROVED** [review]
