### PR TITLE
Fix query assistant fetching agent bug

### LINKED ISSUE #7803: [BUG] query_enhancements "Get agent `os_query_assist_ppl` failed, reason: getting agent_id from undefined"
**Describe the bug**
I'm testing query_enhancements's query assistant feature. When I input a natural language question, dashboard pops up error saying "Get agent 'os_query_assist_ppl'  failed, reason: configuration is undefined". 

It's because `configuration` is not in the response of getting agent API, it's `ml_configuration` now.

Sample response:
```
{
	"config_type": "os_query_assist_ppl_agent",
	"ml_configuration": {
		"agent_id": "nIy2MJEBu0iSk2-nBhti"
	}
}
```

**To Reproduce**

**Expected behavior**

**OpenSearch Version**
3.0.0

**Dashboards Version**
3.0.0

**Plugins**
query_enhancements

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

### PR DESCRIPTION
**Pull request by chishui**
### Description

Fix bug https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7803

### Issues Resolved
#7803 

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by joshuali925 — DISMISSED** [review]
didn't know ml-commons API had this breaking change, thanks

File: src/plugins/query_enhancements/server/routes/query_assist/agents.ts [hunk 1]
```diff
@@ -37,11 +37,13 @@ export const getAgentIdByConfig = async (
       method: 'GET',
       path: `${URI.ML}/config/${configName}`,
     })) as ApiResponse<{ type: string; configuration: { agent_id?: string } }>;
-
-    if (!response || response.body.configuration.agent_id === undefined) {
+    if (
+      !response ||
+      !(response.body.ml_configuration?.agent_id || response.body.configuration?.agent_id)
```
Comment (joshuali925) [inline src/plugins/query_enhancements/server/routes/query_assist/agents.ts:42]: do we need to support both keys? i think we do because query assist for MDS clusters can have older version of ml-commons

might be better to add a test to ensure both `configuration` and `ml_configuration` are supported. currently it only tests `configuration`
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/9f3bbe8be6daf23f2c0577035abecb3686b01c06/src/plugins/query_enhancements/server/routes/query_assist/agents.test.ts#L41

**Review by ruanyl — APPROVED** [review]

**Review by SuZhou-Joe — APPROVED** [review]
