### PR TITLE
Fix add filter for numeric scripted field

### LINKED ISSUE #6996: [BUG] is filter not working with numeric Scripted fields
**Describe the bug**
Adding filters for scripted numeric fields using `is` operator after clicking the **Add Filter** Button does not produce any result. However directly clicking on a visualization containing the required field adds the filter correctly. This behavior is observed across visualizations. (Tested the behavior in VisBuilder & Vertical bar Visualization)

**Payload sent while using the Add Filter button**
[PayloadAddFilter.json](https://github.com/user-attachments/files/15779561/PayloadAddFilter.json)
**Payload being sent while clicking on the visualization directly**
[PayloadVisualization.json](https://github.com/user-attachments/files/15779562/PayloadVisualization.json)

Upon analysis of Payloads, the following observation was found.
When using the Add Filter button, The value is being sent as string.
`"value": "66"`
While when we are using the visualization to filter it sends the 
`"value": 66`

This explains why we are not getting the expected results with the Add Filter option in case of numeric fields  since we are sending the value as string. 

**Expected behavior**
Add Filter should work with scripted numeric fields while using the is operator.

**OpenSearch Version**
3.0.0-snapshot 
**Dashboards Version**
3.0.0

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

Using the Add filter 
image

Clicking on the Visualization 
image

**Host/Environment (please complete the following information):**

 - Browser and version [e.g. 22]
 

**Additional context**

### PR DESCRIPTION
**Pull request by abbyhu2000**
### Description

Fix add filter for numeric scripted field. Previously, adding filters for scripted numeric fields using is operator after clicking the Add Filter Button does not produce any result.

### Issues Resolved
resolves #6996 

## Screenshot

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/8a5e60ad-9639-4ea7-81c4-933d4514d57b

## Changelog

- fix: Fix add filter for numeric scripted field

### CODE REVIEW

File: src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx [hunk 1]
```diff
@@ -147,6 +147,17 @@ class ValueInputTypeUI extends Component<Props> {
...
   };
 
+  private onNumberChange = (event: React.ChangeEvent<HTMLInputElement>) => {
+    const params = event.target.value;
+    this.props.onChange(
+      typeof params === 'string'
+        ? parseFloat(params)
+        : typeof params === 'bigint'
+        ? (params as BigInt).toString()
+        : params
```
Comment (virajsanghvi) [inline src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx:157]: nit: instead of using a nested ternary extract part of it out, use an if/else statement, or use parens in the nested ternary to make it easier to read.

File: src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx [hunk 2]
```diff
@@ -147,6 +147,17 @@ class ValueInputTypeUI extends Component<Props> {
     this.props.onChange(boolValue);
   };
 
+  private onNumberChange = (event: React.ChangeEvent<HTMLInputElement>) => {
```
Comment (virajsanghvi) [inline src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx:150]: Are these cases already covered in unit tests?

File: src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx (hunk 1 above)
Comment (abbyhu2000) [reply src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx]: Changed to if else statement

File: src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx (hunk 2 above)
Comment (abbyhu2000) [reply src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx:150]: This file does not have any unit tests, added unit test for this file.

**Review by ananzh — DISMISSED** [review]

File: src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx (hunk 2 above)
Comment (virajsanghvi) [reply src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx:150]: Thanks for adding the unit tests! Do they cover the change handler you added?

File: src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.test.tsx [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+import { mountWithIntl } from 'test_utils/enzyme_helpers';
+import { ValueInputType } from './value_input_type';
+
+let onChangeMock: any;
+
+describe('Value input type', () => {
+  beforeAll(() => {
+    onChangeMock = jest.fn();
+  });
+  it('is number', async () => {
```
Comment (AMoo-Miki) [inline src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.test.tsx:16]: Do we have tests elsewhere for IPs, Dates, and anything else this input handles? If not, this would be good opportunity to add them.

File: src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.test.tsx [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+    const valueInputProps = {
+      value: 1,
```
Comment (AMoo-Miki) [inline src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.test.tsx:18]: For BigInt, use exactly the same test and only change value to `1n`.

File: src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx [hunk 5]
```diff
@@ -147,6 +147,17 @@ class ValueInputTypeUI extends Component<Props> {
...
+    const params = event.target.value;
+    let numValue;
+    if (typeof params === 'string') {
+      numValue = parseFloat(params);
+    } else if (typeof params === 'bigint') {
+      numValue = (params as BigInt).toString();
```
Comment (AMoo-Miki) [inline src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx:156]: We shouldn't have this. If the value is a BigInt, we should leave it as it.
```suggestion

```

Comment (abbyhu2000) [reply src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx:156]: I added this logics according to previous logics on line 71, https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7022/files/6b7d63232ed9b7b0c8a152ad66c262d41d8b4629#diff-d1ea4f28ecf59eb6ec2702dd4f29cd9a42aeab29c6065fc80c73be1f3ad9825aR71

I see they called `toString()` if the value is Bigint

File: src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.test.tsx (hunk 3 above)
Comment (abbyhu2000) [reply src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.test.tsx:16]: Will add date and ip unit test

File: src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.test.tsx (hunk 4 above)
Comment (abbyhu2000) [reply src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.test.tsx:18]: added a unit test for bigint using 1n

File: src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx (hunk 2 above)
Comment (virajsanghvi) [reply src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx:150]: We don't test the methods directly, but we still need to exercise the logic - otherwise, how are we validating it works? I'm mostly reacting to the lack of code coverage below.

Comment (abbyhu2000) [reply src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx:150]: I agree, but how do we test those private method logics? I thought if the function is not exported by the module, it cannot be called by test code outside the module. Could you provide an example to help me? Thanks!

**Review by ananzh — APPROVED** [review]

File: src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.test.tsx [hunk 6]
```diff
@@ -0,0 +1,87 @@
...
+  it('is number bigint', async () => {
+    const valueInputProps = {
+      value: '1n',
+      type: 'number',
+      onChange: onChangeMock,
+      onBlur: () => {},
+      placeholder: '',
+    };
+    const component = mountWithIntl(<ValueInputType {...valueInputProps} />);
+    expect(component).toMatchSnapshot();
```
Comment (ashwin-pc) [inline src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.test.tsx:37]: Can we not use snapshot tests here? Taking a look at the snapshot and they dont offer much value here

File: src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx (hunk 5 above)
Comment (ashwin-pc) [inline src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx:156]: Where are we using `numValue`?

Comment (abbyhu2000) [reply src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx:156]: should be `this.props.onChange(numValue);`. It is a typo when addressing later comments

File: src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.test.tsx (hunk 6 above)
Comment (abbyhu2000) [reply src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.test.tsx:37]: I think they do provide values, the unit tests are mainly testing if `switch (this.props.type)` are rendering correct components based on the input type. For example, string type should render <EuiFieldText> with correct placeholder, boolean type should render <EuiSelect> with correct selections.

```
switch (this.props.type) {
      case 'string':
        inputElement = (
          <EuiFieldText
           ...
          />
        );
        break;
      case 'number':
        inputElement = (
          <EuiFieldNumber
            ...
          />
        );
        break;
      case 'date':
        inputElement = (
          <EuiFieldText
            ...
          />
        );
        break;
      case 'ip':
        inputElement = (
          <EuiFieldText
           ...
          />
        );
        break;
      case 'boolean':
        inputElement = (
          <EuiSelect
            fullWidth={this.props.fullWidth}
            options={[...]}
            ...
          />
        );
```

File: src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx (hunk 5 above)
Comment (abbyhu2000) [reply src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx:156]: will fix soon

File: src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.test.tsx (hunk 6 above)
Comment (ashwin-pc) [reply src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.test.tsx:37]: i meant can we just snapshot the value we expect instead of the whole thing. If this test breaks, it should be only because of the changes related to what you are testing. Right now, if the component chnages, these tests will break too. Keep unit tests scoped to just test for just the feature and not anything else. Otherwise when things change, a lot of these test will break.

**Review by ashwin-pc — APPROVED** [review]
Thanks for making the change. This looks good to me

**Review by ananzh — APPROVED** [review]
