### PR TITLE
[MDS] Refactor dropdown header + Aggregate view UI

### LINKED ISSUE #6533: [BUG] Fix text alignment and change to normal cursor in data source aggregated view
**Describe the bug**
When hover over the aggregated view, the cursor should be regular cursor
cursor-read-only

The text for the popover needs to be aligned
Screenshot 2024-04-18 at 7 21 44 AM

**To Reproduce**
1. Go to future playground
2. Click on maps plugin
3. Go to create and open the popover
4. See the behavior

**Expected behavior**

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

### PR DESCRIPTION
**Pull request by huyaboo**
### Description

Refactors the UI Components for the datasource dropdown menu and the aggregate view. Specifically, the `disabled` cursor is removed and the dropdown header has the text vertically aligned. Some minor enhancements also made to aggregate view as well.

### Issues Resolved

#6533 

## Screenshot

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/73027756/c59f67c3-9f5d-49f1-a185-6cc8ae9a2887

## Changelog

- skip

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by BionIT — APPROVED** [review]

**Review by zhyuanqi — APPROVED** [review]

File: src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx [hunk 1]
```diff
@@ -203,15 +203,7 @@ export class DataSourceAggregatedView extends React.Component<
...
-            <EuiPanel
-              className={'dataSourceAggregatedViewOuiPanel'}
-              borderRadius="none"
-              hasBorder={false}
-              color="transparent"
-              paddingSize="s"
-            >
-              {titleComponent}
-            </EuiPanel>
+            {titleComponent}
```
Comment (zhyuanqi) [inline src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx:206]: This is minor. I think the titleComponet should be outside EuiContextMenuPanel since it is using a EuiPopoverTitle. I feel like it is not part of the EuiContextMenuPanel

Comment (huyaboo) [reply src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx]: Fixed.

Comment (zhyuanqi) [reply src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx]: Thanks

**Review by zhongnansu — APPROVED** [review]
lgtm!

**Review by BionIT — DISMISSED** [review]

**Review by BionIT — APPROVED** [review]

**Review by zhongnansu — APPROVED** [review]
