### PR TITLE
[Dashboard] Fix bugs on removing pinned global filters on dashboard page

### LINKED ISSUE #4767: [BUG] Pinned filters do not work and do not update visualisations when added or removed
Pinned filters seem to be broken in v2.9.0 and do not seem to work at all.  Adding or removing a pinned filter does not trigger a new OpenSearch request in the background for data including the filter.

**To Reproduce**
1. Go to any visualisation or Dashboard - for this issue you can reproduce with this [playground link](https://playground.opensearch.org/app/dashboards#/view/edf84fe0-e1a0-11e7-b6d5-4dc382ef7f5b?_g=(filters%3A!()%2CrefreshInterval%3A(pause%3A!f%2Cvalue%3A900000)%2Ctime%3A(from%3Anow-7d%2Cto%3Anow)))
2. Add a filter to the visualisation (e.g. with the above link select a country from the dropdown)
3. Notice that the data is correctly filtered
4. Click the filter and then "Pin across all apps"
5. Click the x button on the filter to remove the filter
6. Notice that nothing changes.  The filter still persists.

If you check the browser network requests, you will find that no new OpenSearch request was made when the filter was removed.

This can also be reproduced by turning on "Pin filters by default" in the Advanced settings (which won't work on playground).  When filters are added, the visualisation or dashboard will not update and filters are completely broken unless unpinned.

**OpenSearch Version**
2.9.0

**Dashboards Version**
2.9.0

**Host/Environment (please complete the following information):**
Windows, Firefox 102.14.0esr & Chrome 115.0.5790.111

**Additional context**
This previously had worked in 2.7.0.

### PR DESCRIPTION
**Pull request by abbyhu2000**
### Description
This PR fixes the error removing pinned global filters.

Previously removing pinned global filters needs a refresh for it to be effective on the dashboard because it does not get updated immediately from global states to the dashboard container. Previously the dashboard container only listens to the app filters, this PR adds a listener on the global filter for the dashboard container.

### Issues Resolved
resolves #4767 

## Screenshot

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/76d48847-a4ca-4ebf-a66d-acfd2409ea05

### CODE REVIEW

File: src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.tsx [hunk 1]
```diff
@@ -193,6 +193,17 @@ export const useDashboardAppAndGlobalState = ({
 
         subscriptions.add(stopSyncingFromTimeFilters);
 
+        const stopSyncingFromGlobalFilters = filterManager.getUpdates$().subscribe(() => {
```
Comment (ashwin-pc) [inline src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.tsx:196]: Shouldnt we unsubscribe from this when exiting the hook?

**Review by ananzh — APPROVED** [review]

File: src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.tsx (hunk 1 above)
Comment (abbyhu2000) [reply src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.tsx:196]: i did unsubscribe by `subscriptions.add(stopSyncingFromGlobalFilters);` and `subscriptions.unsubscribe();`

**Review by AMoo-Miki — APPROVED** [review]

**Comment by joshuarrrr** [comment]
@abbyhu2000 any plans to also add a regression test for this? Maybe in the functional tests?
