### PR TITLE
Highlight the anchor row in surrounding doc view

### LINKED ISSUE #6457: [BUG] When using the "View surrounding documents" function the main event is not highlighted
**Describe the bug**
When using the "View surrounding documents" function the main event is not highlighted

**Expected behavior**
I would really like to see the implementation of version 2.9

**OpenSearch Version**
2.13

**Dashboards Version**
2.13

**Plugins**

Please list all plugins currently enabled.

**Screenshots**
In version 2.9 it was like this:
old

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

### PR DESCRIPTION
**Pull request by abbyhu2000**
### Description
Highlight the anchor row in surrounding doc view. 

### Issues Resolved
resolves #6457 

## Screenshot

Screenshot 2024-06-13 at 3 04 49 PM

## Changelog
- fix:Highlight the anchor row in surrounding doc view

### CODE REVIEW

File: src/plugins/discover/public/application/components/default_discover_table/table_row.tsx [hunk 1]
```diff
@@ -48,7 +48,7 @@ const TableRowUI = ({
   ]);
 
   const tableRow = (
-    <tr key={row._id}>
+    <tr key={row._id} className={row.isAnchor ? 'osdDocTable__row--highlight' : ''}>
```
Comment (virajsanghvi) [inline src/plugins/discover/public/application/components/default_discover_table/table_row.tsx:51]: Is there a test for this or is it covered in some other way?

Comment (abbyhu2000) [reply src/plugins/discover/public/application/components/default_discover_table/table_row.tsx:51]: I don't think default discover table is covered by any unit tests. src/plugins/discover/public/application/components/default_discover_table

Comment (ananzh) [reply src/plugins/discover/public/application/components/default_discover_table/table_row.tsx:51]: Should we add a ftr test? cuz we want to gradually build up the test coverage.

Comment (abbyhu2000) [reply src/plugins/discover/public/application/components/default_discover_table/table_row.tsx:51]: I think we want to add unit tests and functional tests for default discover table overall. Created an issue to track it here: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7048

**Review by ananzh — APPROVED** [review]

File: src/plugins/discover/public/application/doc_views/doc_views_types.ts [hunk 2]
```diff
@@ -32,7 +32,9 @@ import { ComponentType } from 'react';
 import { SearchResponse } from 'elasticsearch';
 import { IndexPattern } from '../../../../data/public';
 
-export type OpenSearchSearchHit<T = unknown> = SearchResponse<T>['hits']['hits'][number];
+export type OpenSearchSearchHit<T = unknown> = SearchResponse<T>['hits']['hits'][number] & {
```
Comment (kavilla) [inline src/plugins/discover/public/application/doc_views/doc_views_types.ts:35]: nit: the name `OpenSearchSearchHit` is confusing for me because it seems like OpenSearch is returning back to us if it is an anchor or not. Can we create another alias for this to be more descriptive that shims to the hit response if it isAnchor or not based on the context?

that would help me as well not worry if there is potential issues changing the type (even though it is just an optional field). if this type is actually only used within Discover in context then perhaps the name can be reconsidered since `OpenSearchSearchHit` implies to me it has more purposes than just for table rows.

**Review by virajsanghvi — APPROVED** [review]
approving assuming its going to be tested in tracked issue

**Review by kavilla — APPROVED** [review]
