### PR TITLE
[Data Explorer] Adds support for line count

### LINKED ISSUE #5404: [BUG] No line wrapping when displaying fields (dashboard v 2.11)
**Describe the bug**
The functionality of the Discover section has deteriorated after updating Opensearch-dashboard to version 2.11.
No line wrapping when displaying fields.
It is very inconvenient to work with long text fields.

**To Reproduce**
Go to the Discover section.
Select multiple long fields

**Expected behavior**
Fields are displayed in several lines

**OpenSearch Version**
2.11

**Dashboards Version**
2.11

**Plugins**

**Screenshots**
Top screenshot version 2.9
Bottom screenshot version 2.11

os-dash

**Host/Environment (please complete the following information):**
 - OS: Windows 10
 - Browser and version: Firefox119.0  

**Additional context**

### PR DESCRIPTION
**Pull request by ashwin-pc**
### Description

Adds support for user selectable row heights

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/20453492/a83dcfb8-500f-400f-a6c9-63be8e00c360

### Issues Resolved

fixes #5404 

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

File: src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx [hunk 1]
```diff
@@ -208,7 +214,7 @@ export const DataGridTable = ({
         renderCellValue={renderCellValue}
         rowCount={rowCount}
         sorting={sorting}
-        toolbarVisibility={isToolbarVisible ? toolbarVisibility : false}
+        toolbarVisibility={isToolbarVisible ? toolbarOptions : false}
```
Comment (AMoo-Miki) [inline src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx:217]: The name of this prop gives an impression of being an object, and not a boolean value.

**Review by AMoo-Miki — APPROVED** [review]

File: src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx (hunk 1 above)
Comment (ashwin-pc) [reply src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx:217]: It is an object. Thats why i think the OUI prop name here is actually pretty bad, but thats problem thats out of scope for this issue.
