### PR TITLE
[BUG] Fix permission check failed with empty workspace for find method

### LINKED ISSUE #6528: [BUG][Workspace] Permission check failed with empty workspace array
**Describe the bug**

when doing permission check, it will filter workspace list and verify there at least have 1 workspace user have permission, otherwise it will throw exception.

The bug is that, if we pass an empty array, that will go through this check and throw exception.

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts#L469-L490

**To Reproduce**

**Expected behavior**

**OpenSearch Version**
main

**Dashboards Version**
main

**Plugins**

workspace

**Screenshots**

**Host/Environment (please complete the following information):**
main

**Additional context**

### PR DESCRIPTION
**Pull request by Hailong-am**
### Description

when doing permission check, it will filter workspace list and verify there at least have 1 workspace user have permission, otherwise it will throw exception.

The bug is that, if we pass an empty array, that will go through this check and throw exception.

### Issues Resolved

#6528

## Changelog

- fix: permission check failed with empty workspace for find method

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by SuZhou-Joe — APPROVED** [review]

File: src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts [hunk 1]
```diff
@@ -466,7 +466,7 @@ export class WorkspaceSavedObjectsClientWrapper {
           })
         ).saved_objects.map((item) => item.id);
 
-        if (options.workspaces) {
+        if (options.workspaces && options.workspaces.length > 0) {
```
Comment (wanglam) [inline src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts:469]: Shall we add some UT or IT to cover this line?

Comment (Hailong-am) [reply src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts:469]: sure, let met add a test case

File: src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts [hunk 2]
```diff
@@ -560,6 +560,52 @@ describe('WorkspaceSavedObjectsClientWrapper', () => {
           },
         });
       });
+      it('should call client.find with ACLSearchParams if no workspaces is provided', async () => {
+        const { wrapper, clientMock } = generateWorkspaceSavedObjectsClientWrapper();
+        // no workspaces
+        await wrapper.find({
+          type: 'dashboards',
+        });
+        expect(clientMock.find).toHaveBeenCalledWith({
```
Comment (wanglam) [inline src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts:569]: Since `clientMock.find` will be called multi times, prefer using `toHaveBeenLastCalledWith`

Comment (Hailong-am) [reply src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts:569]: good catch.

**Review by SuZhou-Joe — APPROVED** [review]

**Review by wanglam — APPROVED** [review]

**Review by ruanyl — APPROVED** [review]
