### PR TITLE
[Discover 2.0] fixes add filter and dismissible callout

### LINKED ISSUE #5027: [BUG] Dashboards RC 2.10.0.6565 filter button in discover app doesn't work
**Describe the bug**

Filter button in facetted search doesn't work. Confirmed on the latest releases of Brave and Firefox, see video. 

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/2643715/906cdba6-93a0-435b-ab2b-be7a1da578cf

**Expected behavior**
when clicking the + icon the filter is applied

**OpenSearch Version**
2.10.0.8459 Docker container

**Dashboards Version**
Dashboards RC 2.10.0.6565 Docker container

**Plugins**

Defaults + S3 repository plugin

**Screenshots**

**Host/Environment (please complete the following information):**
Macos Ventura

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by ashwin-pc**
### Description

This fixes 4 small issues:

1. Fixes the add filter in the sidebar for discover 2.0
2. Fixes the deprecation notice not persisting on page refresh
3. Loads the filters and query from a saved search
4. minor type errors.

### Issues Resolved

fixes #5027

## Screenshot

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/20453492/36fc7c2c-ddf0-493f-b382-05126c193862

## Testing the changes

Pull down the changes and open the discover app. Adding filters in the side panel should work. The dismissable callout should stay dismissed after the page refresh.

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by ananzh — DISMISSED** [review]

**Review by abbyhu2000 — DISMISSED** [review]

File: src/plugins/discover/public/application/view_components/utils/use_search.ts [hunk 1]
```diff
@@ -8,6 +8,7 @@ import { BehaviorSubject, Subject, merge } from 'rxjs';
 import { debounceTime } from 'rxjs/operators';
 import { i18n } from '@osd/i18n';
 import { useEffect } from 'react';
+import { cloneDeep } from 'lodash';
```
Comment (kavilla) [inline src/plugins/discover/public/application/view_components/utils/use_search.ts:11]: probably will be apart of a future "remove lodash" epic right

similar issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4349

**Review by kavilla — APPROVED** [review]

**Review by abbyhu2000 — APPROVED** [review]

File: src/plugins/discover/public/application/view_components/utils/use_search.ts (hunk 1 above)
Comment (ashwin-pc) [reply src/plugins/discover/public/application/view_components/utils/use_search.ts:11]: yep, this is how the legacy app did it and i didnt want to refactor this right now

**Comment by kavilla** [comment]
@ashwin-pc I'm going to watch this bake in 2.x. Instead of waiting for main to finish and then opening and waiting another hour for 2.x, 2.10
